export const SENDING_ATTACHMENT = 'SENDING_ATTACHMENT';
export const ATTACHMENT_SENT = 'ATTACHMENT_SENT';

export const MESSENGER_TOGGLE = 'MESSENGER_TOGGLE';
export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const CHANGE_CONVERSATION = 'CHANGE_CONVERSATION';
export const ASK_EMAIL = 'ASK_EMAIL';
export const SAVED_EMAIL = 'SAVED_EMAIL';
