export const SENDING_ATTACHMENT = 'SENDING_ATTACHMENT';
export const ATTACHMENT_SENT = 'ATTACHMENT_SENT';
export const MESSAGE_SENT = 'MESSAGE_SENT';

export const MESSENGER_TOGGLE = 'MESSENGER_TOGGLE';
export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const CHANGE_CONVERSATION = 'CHANGE_CONVERSATION';
export const END_CONVERSATION = 'END_CONVERSATION';
export const ENGAGE_MESSAGES_CREATED = 'ENGAGE_MESSAGES_CREATED';
