export const SENDING_ATTACHMENT = 'SENDING_ATTACHMENT';
export const ATTACHMENT_SENT = 'ATTACHMENT_SENT';

export const MESSENGER_TOGGLE = 'MESSENGER_TOGGLE';
export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const CHANGE_CONVERSATION = 'CHANGE_CONVERSATION';
export const ASK_GET_NOTIFIED = 'ASK_GET_NOTIFIED';
export const GET_NOTIFIED_VALUE_SAVED = 'GET_NOTIFIED_VALUE_SAVED';
export const END_CONVERSATION = 'END_CONVERSATION';
