import { StyleSheet } from '@react-pdf/renderer';
import { PDF_FONT_FAMILY, PDF_FONT_FAMILY_SERIF } from './fonts';
import { COLORS } from './styles';

const PAPER = '#f7f1ea';

export const editorialStyles = StyleSheet.create({
  coverPage: {
    fontFamily: PDF_FONT_FAMILY,
    padding: 0,
    margin: 0,
    backgroundColor: PAPER,
  },
  coverWrapper: {
    width: 595.28,
    height: 841.89,
    position: 'relative',
    backgroundColor: PAPER,
    paddingTop: 42,
    paddingLeft: 44,
    paddingRight: 44,
    paddingBottom: 42,
  },
  paperTextureBar: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 18,
    backgroundColor: '#ece3d8',
  },
  headerLogoRow: {
    minHeight: 40,
    justifyContent: 'center',
    marginBottom: 18,
  },
  itineraryNameBanner: {
    marginBottom: 30,
    paddingRight: 32,
  },
  itineraryNameText: {
    fontFamily: PDF_FONT_FAMILY_SERIF,
    fontSize: 27,
    color: '#2c231f',
    lineHeight: 1.2,
    letterSpacing: -0.4,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  itineraryNameSubtext: {
    fontSize: 8,
    color: '#9a897c',
    textTransform: 'uppercase',
    letterSpacing: 1.8,
    marginBottom: 11,
  },
  itineraryNameDivider: {
    width: 116,
    height: 1,
    backgroundColor: '#bbaa9d',
  },
  coverBody: {
    flexDirection: 'row',
    gap: 24,
    alignItems: 'stretch',
    flex: 1,
  },
  coverImageColumn: {
    width: 132,
    position: 'relative',
  },
  coverImageFrame: {
    width: 118,
    height: 290,
    backgroundColor: '#ddd1c4',
    padding: 8,
  },
  coverImageAccent: {
    position: 'absolute',
    top: 122,
    right: -8,
    width: 10,
    height: 170,
    backgroundColor: '#ddd1c4',
  },
  coverImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  dayBadge: {
    position: 'absolute',
    top: 14,
    left: 14,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: '#d9cdc1',
    paddingVertical: 8,
    paddingHorizontal: 14,
  },
  dayBadgeText: {
    fontFamily: PDF_FONT_FAMILY_SERIF,
    fontSize: 11,
    color: '#463b35',
    textTransform: 'uppercase',
    fontWeight: 'bold',
  },
  coverContentColumn: {
    flex: 1,
    paddingTop: 26,
  },
  coverTitle: {
    fontFamily: PDF_FONT_FAMILY_SERIF,
    fontWeight: 'bold',
    fontSize: 24,
    color: '#2e2521',
    textTransform: 'uppercase',
    lineHeight: 1.3,
    marginBottom: 10,
  },
  coverDivider: {
    width: 72,
    height: 2,
    marginBottom: 14,
    backgroundColor: '#57453d',
  },
  coverMeta: {
    fontFamily: PDF_FONT_FAMILY,
    fontWeight: 'bold',
    fontSize: 10,
    color: '#544740',
    lineHeight: 1.7,
    marginBottom: 18,
  },
  coverDescription: {
    fontSize: 10,
    color: '#5c514a',
    lineHeight: 1.75,
  },
  coverLogoContainer: {
    position: 'absolute',
    right: 44,
    bottom: 36,
  },
  coverLogo: {
    width: 86,
    height: 38,
    objectFit: 'contain',
  },
  page: {
    fontFamily: PDF_FONT_FAMILY,
    fontSize: 10,
    color: COLORS.text,
    paddingTop: 38,
    paddingBottom: 42,
    paddingLeft: 48,
    paddingRight: 48,
    backgroundColor: PAPER,
    position: 'relative',
  },
  pageHeader: {
    marginBottom: 28,
  },
  pageHeaderLogo: {
    width: 108,
    height: 40,
    objectFit: 'contain',
  },
  dayBlock: {
    marginBottom: 24,
  },
  dayBlockReverse: {
    flexDirection: 'row-reverse',
  },
  dayLayout: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 24,
  },
  dayImageColumn: {
    width: 132,
    position: 'relative',
  },
  dayImageFrame: {
    width: 122,
    height: 168,
    backgroundColor: '#d9ccbf',
    padding: 7,
  },
  dayImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  dayImageFallback: {
    width: '100%',
    height: '100%',
    backgroundColor: '#e6d9cc',
  },
  dayTextColumn: {
    flex: 1,
    paddingTop: 10,
  },
  dayTitle: {
    fontFamily: PDF_FONT_FAMILY_SERIF,
    fontWeight: 'bold',
    fontSize: 19,
    color: '#2d2520',
    lineHeight: 1.24,
    marginBottom: 7,
  },
  dayDivider: {
    width: 62,
    height: 1,
    backgroundColor: '#5f4f45',
    marginBottom: 10,
  },
  dayContentGroup: {
    width: '100%',
  },
  dayContent: {
    fontSize: 9.1,
    color: '#5a4e47',
    lineHeight: 1.72,
  },
  dayContentParagraph: {
    marginBottom: 7,
  },
  noItineraryText: {
    fontSize: 11,
    color: COLORS.gray,
    fontStyle: 'italic',
    marginTop: 40,
  },
  fixedFooter: {
    position: 'absolute',
    bottom: 16,
    left: 48,
    right: 48,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#ded2c6',
    paddingTop: 6,
  },
  fixedFooterText: {
    fontSize: 7,
    color: '#8b7f75',
  },
  footerPage: {
    fontFamily: PDF_FONT_FAMILY,
    fontSize: 10,
    color: COLORS.text,
    paddingTop: 42,
    paddingBottom: 42,
    paddingLeft: 48,
    paddingRight: 48,
    backgroundColor: PAPER,
    position: 'relative',
  },
  footerBody: {
    marginTop: 18,
  },
  footerNotesBlock: {
    marginBottom: 16,
  },
  footerHint: {
    fontSize: 9,
    color: '#665951',
    lineHeight: 1.7,
  },
});
