import {
  Configs,
  DonateCampaigns,
  Donates,
  VoucherCampaigns,
  Vouchers,
  SpinCampaigns,
  Spins,
  LotteryCampaigns,
  Lotteries,
  Loyalties,
  ScoreLogs,
  Assignments,
  AssignmentCampaigns,
  ScoreCampaigns,
  Agents,
  CouponCampaigns,
  Coupons,
} from '~/modules/loyalty/graphql/resolvers/mutations';

export const mutations = {
  ...Configs,
  ...DonateCampaigns,
  ...Donates,
  ...VoucherCampaigns,
  ...Vouchers,
  ...SpinCampaigns,
  ...Spins,
  ...LotteryCampaigns,
  ...Lotteries,
  ...Loyalties,
  ...ScoreLogs,
  ...Assignments,
  ...AssignmentCampaigns,
  ...ScoreCampaigns,
  ...Agents,
  ...CouponCampaigns,
  ...Coupons,
};
