pipeline:
  ping:
    image: mongo:3.6
    commands:
      - sleep 15
      - mongo --host mongo

  test:
    image: erxes/runner:latest
    environment:
      - TEST_MONGO_URL=mongodb://mongo/test
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn install
      - yarn lint
      - yarn tsc
      - mkdir src/private/xlsTemplateOutputs
      - yarn test

  build:
    image: erxes/runner:latest
    commands:
      - apt-get update && apt-get install -y git
      - git checkout $DRONE_COMMIT_BRANCH
      - yarn build
    when:
      branch:
        - master
        - develop
      event:
        - push

  build_tag:
    image: erxes/runner:latest
    commands:
      - yarn build
      - tar -zcf ${DRONE_REPO_NAME}_${DRONE_TAG}.tar.gz dist initialData src .env.sample package.json yarn.lock
    when:
      event:
        - tag

  docker_publish:
    image: plugins/docker
    repo: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
    dockerfile: Dockerfile
    secrets:
      - source: docker_hub_username
        target: docker_username
      - source: docker_hub_password
        target: docker_password
    tags:
      - ${DRONE_BRANCH}
    when:
      branch:
        - master
        - develop
      event:
        - push

  docker_publish_tag:
    image: plugins/docker
    repo: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
    dockerfile: Dockerfile
    secrets:
      - source: docker_hub_username
        target: docker_username
      - source: docker_hub_password
        target: docker_password
    tags:
      - ${DRONE_TAG}
    when:
      event:
        - tag

  github_prerelease:
    image: plugins/github-release
    secrets: [ github_token ]
    prerelease: true
    files:
      - ${DRONE_REPO_NAME}_${DRONE_TAG}.tar.gz
    checksum:
      - sha256
    when:
      event:
        - tag
      ref:
        include:
          - "refs/tags/*rc*"
          - "refs/tags/*alpha*"
          - "refs/tags/*beta*"
    # draft: true

  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - ${DRONE_REPO_NAME}_${DRONE_TAG}.tar.gz
    checksum:
      - sha256
    when:
      event:
        - tag
      ref:
        include:
          - "refs/tags/*"
        exclude:
          - "refs/tags/*rc*"
          - "refs/tags/*alpha*"
          - "refs/tags/*beta*"
    # draft: true

services:
  mongo:
    image: mongo:3.6
    command: [--smallfiles]