pipeline:
  install:
    image: node:10.16.0-slim
    commands:
      - yarn install
      - yarn lint
      - yarn tsc

  build:
    image: node:10.16.0-slim
    commands:
      - yarn build
    when:
      branch:
        - master
        - develop
      event:
        - push
        - tag

  docker:
    image: plugins/docker
    repo: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
    dockerfile: Dockerfile
    secrets:
      - source: docker_hub_username
        target: docker_username
      - source: docker_hub_password
        target: docker_password
    tags:
      - ${DRONE_BRANCH}
    when:
      branch:
        - master
        - develop
      event:
        - push