module.exports = {
  automations: false,
  calendar: false,
  clientportal: false,
  engages: false,
  internalnotes: false,
  knowledgebase: false,
  logs: false,
  notifications: false,
  segments: false,
  tags: false,
  integrations: false,
  products: false,
  forms: false,
  cards: false,
  emailTemplates: false,
  contacts: false,
  inbox: false,
};
