module.exports = [
  "automations",
  "calendar",
  "clientportal",
  "engages",
  "internalnotes",
  "knowledgebase",
  "logs",
  "notifications",
  "segments",
  "tags",
  "integrations",
  "products",
  "forms",
  "cards",
  "emailTemplates",
  "contacts",
  "inbox"
]