export const CONFIG_KEYS = {
  ORCHARD_API_URL: 'ORCHARD_API_URL',
  ORCHARD_USERNAME: 'ORCHARD_USERNAME',
  ORCHARD_PASSWORD: 'ORCHARD_PASSWORD',

  ALL: ['ORCHARD_API_URL', 'ORCHARD_USERNAME', 'ORCHARD_PASSWORD']
};
