export const ACTIVITY_CONTENT_TYPES = {
  CUSTOMER: 'customer',
  COMPANY: 'company',
  USER: 'user',
  DEAL: 'deal',
  TICKET: 'ticket',
  TASK: 'task',
  PRODUCT: 'product',
  GROWTH_HACK: 'growthHack',
  SMS: 'sms',
  CAMPAIGN: 'campaign',
  INTERNAL_NOTE: 'internal_note',
  CHECKLIST: 'checklist',
  CONVERSATION: 'conversation',
  SEGMENT: 'segment',
  EMAIL: 'email',
  BRAND: 'brand',

  ALL: [
    'customer',
    'company',
    'user',
    'deal',
    'ticket',
    'task',
    'product',
    'growthHack',
    'sms',
    'campaign',
    'internal_note',
    'checklist',
    'conversation',
    'segment',
    'email',
    'brand',
  ],
};

export const ACTIVITY_ACTIONS = {
  CREATE: 'create',
  UPDATE: 'update',
  DELETE: 'delete',
  MERGE: 'merge',
  SEND: 'send',
  MOVED: 'moved',
  CONVERT: 'convert',
  ASSIGNEE: 'assignee',
  TAGGED: 'tagged',

  ALL: [
    'create',
    'update',
    'delete',
    'merge',
    'send',
    'moved',
    'convert',
    'assignee',
    'tagged'
  ]
};
