export const menuDynamic = [
  { title: 'Sync History', link: '/sync-msdynamic-history' },
  { title: 'Check Categories', link: '/msdynamic-category' },
  { title: 'Check Products', link: '/msdynamic-products' },
  { title: 'Check Price', link: '/msdynamic-price' },
  { title: 'Check Customers', link: '/msdynamic-customers' },
];

export const KEY_LABELS = {
  itemApi: 'item api',
  itemCategoryApi: 'item category api',
  priceApi: 'price api',
  customerApi: 'customer api',
  salesApi: 'sales api',
  salesLineApi: 'sales line api',
  username: 'username',
  password: 'password',
  genBusPostingGroup: 'Gen_Bus_Posting_Group',
  vatBusPostingGroup: 'VAT_Bus_Posting_Group',
  customerPostingGroup: 'Customer Posting Group',
  customerPricingGroup: 'Customer Pricing Group',
  customerDiscGroup: 'Customer Disc Group',
  paymentTermsCode: 'Payment Terms Code',
  paymentMethodCode: 'Payment Method Code',
  locationCode: 'Location Code',
  responsibilityCenter: 'Responsibility center',
  billType: 'Bill Type',
  dealType: 'Deal type',
  syncType: 'Sync type',
};
