export const LANGUAGES = [
  { label: 'English', value: 'en' },
  { label: 'Mongolian', value: 'mn' },
  { label: 'French', value: 'fr' },
  { label: 'Deustch', value: 'de' },
  { label: 'Italian', value: 'it' },
  { label: 'Korean', value: 'ko' },
  { label: 'Spanish', value: 'es' },
  { label: 'Portuguese', value: 'pt-br' },
  { label: 'Japanese', value: 'ja' },
  { label: 'Russian', value: 'ru' },
  { label: 'Chinese', value: 'zh-cn' },
  { label: 'Hindi', value: 'hi' },
  { label: 'Vietnam', value: 'vi' },
  { label: 'Indonesian', value: 'yi' }
];

export const MEASUREMENTS = [
  { label: 'Bag BG', value: 'BG' },
  { label: 'Barrel BA', value: 'BA' },
  { label: 'Bolt BT', value: 'BT' },
  { label: 'Box BOX', value: 'BOX' },
  { label: 'Bunch BH', value: 'BH' },
  { label: 'Bundle BE', value: 'BE' },
  { label: 'Butt BU', value: 'BU' },
  { label: 'Canister CI', value: 'CI' },
  { label: 'Carton CT', value: 'CT' },
  { label: 'Case CS', value: 'CS' },
  { label: 'Centimeter CM', value: 'CM' },
  { label: 'Container CON', value: 'CON' },
  { label: 'Crate CR', value: 'CR' },
  { label: 'Cylinder CY', value: 'CY' },
  { label: 'Dozen DOZ', value: 'DOZ' },
  { label: 'Each/Number EA', value: 'EA' },
  { label: 'Envelope EN', value: 'EN' },
  { label: 'Foot FT', value: 'FT' },
  { label: 'Kilogram KG', value: 'KG' },
  { label: 'Kilograms KGS', value: 'KGS' },
  { label: 'Liter L', value: 'L' },
  { label: 'Man hour H', value: 'H' },
  { label: 'Meter M', value: 'M' },
  { label: 'Package PK', value: 'PK' },
  { label: 'Packet PA', value: 'PA' },
  { label: 'Pair PAR', value: 'PAR' },
  { label: 'Pairs PRS', value: 'PRS' },
  { label: 'Pallet PAL', value: 'PAL' },
  { label: 'Piece PC', value: 'PC' },
  { label: 'Pieces PCS', value: 'PCS' },
  { label: 'Pound LB', value: 'LB' },
  { label: 'Proof Liter PF', value: 'PF' },
  { label: 'Roll ROL', value: 'ROL' },
  { label: 'Set SET', value: 'SET' },
  { label: 'Square Meter SME', value: 'SME' },
  { label: 'Square Yard SYD', value: 'SYD' },
  { label: 'Tube TU', value: 'TU' },
  { label: 'Yard YD', value: 'YD' }
];
