export const CHOOSE_RESPONSE_FIELD_DATA = [
  { label: 'Parent Id', value: 'Parent Id' },
  { label: 'Created at', value: 'Created at' },
  { label: 'Name', value: 'Name' },
  { label: 'Start date', value: 'Start date' },
  { label: 'Close date', value: 'Close date' },
  { label: 'Reminder minute', value: 'Reminder minute' },
  { label: 'Is complete', value: 'Is complete' },
  { label: 'Description', value: 'Description' },
  { label: 'Modified at', value: 'Modified at' },
  { label: 'Priority', value: 'Priority' },
  { label: 'Status', value: 'Status' },
  { label: 'Score', value: 'Score' },
  { label: 'Item number', value: 'Item number' },
  { label: 'Total amount', value: 'Total amount' },
  { label: 'UnUsed TotalAmount', value: 'UnUsed TotalAmount' },
  { label: 'Both Total Amount', value: 'Both Total Amount' },
  { label: 'Quantity', value: 'Quantity ' },
  { label: 'Max', value: 'Max' },
  { label: 'Unit price', value: 'Unit price' },
  { label: 'Global unit price', value: 'Global unit price' },
  { label: 'Unit price percent', value: 'Unit price percent' },
  { label: 'Tax percent', value: 'Tax percent' },
  { label: 'Tax', value: 'Tax' },
  { label: 'Discount percent', value: 'Discount percent' },
  { label: 'Discount', value: 'Discount' },
  { label: 'Amount', value: 'Amount' },
  { label: 'Tick used', value: 'Tick used' },
  { label: 'Is vat applied', value: 'Is vat applied' },
  { label: 'Start Date', value: 'Start Date' },
  { label: 'End Date', value: 'End Date' },
  { label: 'Bonus Count', value: 'Bonus Count' },
  { label: 'Created by', value: 'Created by' },
  { label: 'Modified by', value: 'Modified by' },
  { label: 'Assigned to', value: 'Assigned to' },
  { label: 'Watched users', value: 'Watched users' },
  { label: 'Customers full name', value: 'Customers full name' },
  { label: 'Customers Primary Email', value: 'Customers Primary Email' },
  { label: 'Customers Primary Phone', value: 'Customers Primary Phone' },
  { label: 'Customers', value: 'Customers' },
  { label: 'Companies', value: 'Companies' },
  { label: 'Branches', value: 'Branches' },
  { label: 'Departments', value: 'Departments' },
  { label: 'Tags', value: 'Tags' },
  { label: 'Cash', value: 'Cash' },
  { label: 'Barter', value: 'Barter' },
  { label: 'POS', value: 'POS' },
  { label: 'Голомт Банк данс', value: 'Голомт Банк данс' },
  { label: 'Invoice', value: 'Invoice' },
  { label: 'Хаан Банк данс', value: 'Хаан Банк данс' },
  { label: 'Нэхэмжлэх', value: 'Нэхэмжлэх' },
  { label: 'Qpay', value: 'Qpay' },
  { label: 'Product', value: 'Product' },
  { label: 'Product Categories', value: 'Product Categories' },
  { label: 'Assigned to', value: 'Assigned to' },
  { label: 'Stage', value: 'Stage' },
  { label: 'Stage Probability', value: 'Stage Probability' },
];
