import { GET_RELATIONS_BY_ENTITY } from './getRelations';
import { CREATE_RELATIONS, CREATE_MULTIPLE_RELATIONS } from './createRelations';

export { GET_RELATIONS_BY_ENTITY, CREATE_RELATIONS, CREATE_MULTIPLE_RELATIONS };
