export const COMPANY_INFO = {
  primaryName: 'Primary Name',
  size: 'Size',
  industry: 'Industry',
  plan: 'Plan',
  email: 'Email',
  phone: 'Phone',
  leadStatus: 'Lead Status',
  lifecycleState: 'Lifecycle State',
  businessType: 'Business Type',
  description: 'Description',
  doNotDisturb: 'Do not disturb'
};

export const COMPANY_INDUSTRY_TYPES = [
  '',
  'Advertising/Public Relations',
  'Aerospace, Defense Contractors',
  'Agriculture',
  'Airlines',
  'Alcoholic Beverages',
  'Alternative Energy Production & Services',
  'Architectural Services',
  'Attorneys/Law Firms',
  'Automotive',
  'Banks',
  'Bars & Restaurants',
  'Books, Magazines & Newspapers',
  'Builders/General Contractors',
  'Business Services',
  'Car Manufacturers',
  'Coal Mining',
  'Colleges, Universities & Schools',
  'Commercial TV & Radio Stations',
  'Computer Software',
  'Construction',
  'Dairy',
  'Doctors & Other Health Professionals',
  'Education',
  'Energy & Natural Resources',
  'Finance, Insurance & Real Estate',
  'Food & Beverage',
  'Foundations, Philanthropists & Non-Profits',
  'Health',
  'Hotels, Motels & Tourism',
  'Insurance',
  'Internet',
  'Lawyers / Law Firms',
  'Meat processing & products',
  'Medical Supplies',
  'Mining',
  'Mortgage Bankers & Brokers',
  'Music Production',
  'Natural Gas Pipelines',
  'Nursing Homes/Hospitals',
  'Phone Companies',
  'Postal Unions',
  'Printing & Publishing',
  'Private Equity & Investment Firms',
  'Publishing & Printing',
  'Real Estate',
  'Retail Sales',
  'Schools/Education',
  'Sports, Professional',
  'Telecom Services & Equipment',
  'Textiles',
  'Tobacco',
  'Transportation',
  'TV / Movies / Music'
];

export const COMPANY_LEAD_STATUS_TYPES = [
  '',
  'New',
  'Open',
  'In Progress',
  'Open Deal',
  'Unqualified',
  'Attempted to contact',
  'Connected',
  'Bad Timing'
];

export const COMPANY_LIFECYCLE_STATE_TYPES = [
  '',
  'Subscriber',
  'Lead',
  'Marketing Qualified Lead',
  'Sales Qualified Lead',
  'Opportunity',
  'Customer',
  'Evangelist',
  'Other'
];

export const COMPANY_BUSINESS_TYPES = [
  '',
  'Analyst',
  'Competitor',
  'Customer',
  'Integrator',
  'Investor',
  'Partner',
  'Press',
  'Prospect',
  'Reseller',
  'Other'
];
