import { Form, Input, Select, Textarea, Switch } from 'erxes-ui';
import type { FieldValues, UseFormReturn } from 'react-hook-form';
import { CategoryField } from './CategoryField';
import { TagField } from './TagField';
import { LanguageSelector } from '~/modules/cms/shared/LanguageSelector';
import { PostPublicUrlButton } from '../PostPublicUrlButton';
import type { IWebsite } from '~/modules/cms/types';

export type PostUrlField = '_id' | 'count' | 'slug';

export interface PostUrlSource {
  _id?: string;
  count?: number | null;
}

export interface SelectOption {
  label: string;
  value: string;
}

export interface CustomType {
  _id: string;
  label: string;
  code: string;
}

export interface LanguageOption {
  value: string;
  label: string;
  isDefault: boolean;
  hasTranslation: boolean;
}

const POST_URL_FIELD_LABELS: Record<PostUrlField, string> = {
  _id: 'Post ID',
  count: 'Post Count',
  slug: 'Post Slug',
};

const POST_URL_FIELD_DESCRIPTIONS: Record<Exclude<PostUrlField, 'slug'>, string> =
  {
    _id: 'Post ID is generated by the system and used in public post URLs.',
    count: 'Post count is assigned by the system and used in public post URLs.',
  };

const getGeneratedPostUrlValue = (
  postUrlField: Exclude<PostUrlField, 'slug'>,
  fullPost: PostUrlSource | null | undefined,
) => {
  if (postUrlField === '_id') {
    return fullPost?._id || '';
  }

  return typeof fullPost?.count === 'number' ? String(fullPost.count) : '';
};

interface ContentTabProps {
  form: UseFormReturn<FieldValues>;
  categories: SelectOption[];
  tags: SelectOption[];
  customTypes: CustomType[];
  websiteId: string;
  availableLanguages: string[];
  defaultLanguage: string;
  selectedLanguage: string;
  languageOptions: LanguageOption[];
  postUrlField: PostUrlField;
  fullPost: PostUrlSource | null | undefined;
  cmsConfig?: IWebsite;
  handleLanguageChange: (lang: string) => void;
}

export const ContentTab = ({
  form,
  categories,
  tags,
  customTypes,
  websiteId,
  availableLanguages,
  defaultLanguage,
  selectedLanguage,
  languageOptions,
  postUrlField,
  fullPost,
  cmsConfig,
  handleLanguageChange,
}: ContentTabProps) => {
  const isTranslationMode =
    Boolean(selectedLanguage) && selectedLanguage !== defaultLanguage;
  const canShowUrlField = selectedLanguage === defaultLanguage;
  const generatedPostUrlField =
    postUrlField === 'slug' ? undefined : postUrlField;

  return (
    <>
      {availableLanguages.length > 0 && (
        <LanguageSelector
          selectedLanguage={selectedLanguage}
          languageOptions={languageOptions}
          onLanguageChange={handleLanguageChange}
        />
      )}

      <Form.Field
        control={form.control}
        name="type"
        render={({ field }) => (
          <Form.Item>
            <Form.Label>
              Post Type
              {isTranslationMode && (
                <span className="ml-2 text-xs text-gray-500">
                  (shared across languages)
                </span>
              )}
            </Form.Label>
            <Form.Control>
              <Select value={field.value} onValueChange={field.onChange}>
                <Select.Trigger>
                  <Select.Value placeholder="Choose type" />
                </Select.Trigger>
                <Select.Content>
                  <Select.Item value="post">post</Select.Item>
                  {customTypes.map((type) => (
                    <Select.Item key={type._id} value={type._id}>
                      {type.label}
                    </Select.Item>
                  ))}
                </Select.Content>
              </Select>
            </Form.Control>
            <Form.Message />
          </Form.Item>
        )}
      />

      {canShowUrlField && postUrlField === 'slug' && (
        <Form.Field
          control={form.control}
          name="slug"
          render={({ field }) => (
            <Form.Item>
              <Form.Label>{POST_URL_FIELD_LABELS.slug}</Form.Label>
              <Form.Control>
                <div className="flex items-center gap-2">
                  <Input
                    {...field}
                    className="flex-1"
                    placeholder="optional-post-url-slug"
                  />
                  {fullPost && (
                    <PostPublicUrlButton
                      post={fullPost}
                      cmsConfig={cmsConfig}
                      iconOnly
                    />
                  )}
                </div>
              </Form.Control>
              <Form.Description>
                Leave empty to generate from the post title.
              </Form.Description>
              <Form.Message />
            </Form.Item>
          )}
        />
      )}

      {canShowUrlField && generatedPostUrlField && (
        <Form.Item>
          <Form.Label>{POST_URL_FIELD_LABELS[generatedPostUrlField]}</Form.Label>
          <Form.Control>
            <div className="flex items-center gap-2">
              <Input
                value={getGeneratedPostUrlValue(
                  generatedPostUrlField,
                  fullPost,
                )}
                className="flex-1"
                placeholder="Generated after save"
                readOnly
              />
              {fullPost && (
                <PostPublicUrlButton
                  post={fullPost}
                  cmsConfig={cmsConfig}
                  iconOnly
                />
              )}
            </div>
          </Form.Control>
          <Form.Description>
            {POST_URL_FIELD_DESCRIPTIONS[generatedPostUrlField]}
          </Form.Description>
        </Form.Item>
      )}

      <Form.Field
        control={form.control}
        name="description"
        render={({ field }) => (
          <Form.Item>
            <Form.Label>
              Short Description
              {isTranslationMode && (
                <span className="ml-2 text-xs text-blue-600">
                  ({selectedLanguage})
                </span>
              )}
            </Form.Label>
            <Form.Control>
              <Textarea
                {...field}
                placeholder="Description here"
                rows={8}
                maxLength={500}
              />
            </Form.Control>
            <div className="text-xs text-muted-foreground text-right">
              {field.value?.length || 0}/500 characters
            </div>
            <Form.Message />
          </Form.Item>
        )}
      />

      <CategoryField
        form={form}
        categories={categories}
        websiteId={websiteId}
      />
      <TagField form={form} tags={tags} websiteId={websiteId} />

      <Form.Field
        control={form.control}
        name="featured"
        render={({ field }) => (
          <Form.Item>
            <Form.Label>Featured</Form.Label>
            <Form.Description>
              Turn this post into a featured post
            </Form.Description>
            <Form.Control>
              <Switch
                checked={Boolean(field.value)}
                onCheckedChange={field.onChange}
              />
            </Form.Control>
            <Form.Message />
          </Form.Item>
        )}
      />
    </>
  );
};
