export const USER_ACTIVITY_FIELDS = [
  { field: 'email', label: 'Email' },
  { field: 'code', label: 'Code' },
  { field: 'username', label: 'Username' },
  { field: 'employeeId', label: 'Employee Id' },
  { field: 'details.firstName', label: 'First Name' },
  { field: 'details.lastName', label: 'Last Name' },
  { field: 'details.email', label: 'Email' },
  { field: 'details.phone', label: 'Phone' },
  { field: 'details.address', label: 'Address' },
  { field: 'details.city', label: 'City' },
  { field: 'details.state', label: 'State' },
  { field: 'details.birthDate', label: 'Birth Date' },
  { field: 'details.workStartedDate', label: 'Work Started Date' },
  { field: 'details.location', label: 'Location' },
  { field: 'details.description', label: 'Description' },
  { field: 'details.operatorPhone', label: 'Operator Phone' },
  { field: 'details.position', label: 'Position' },
  { field: 'details.shortName', label: 'Short Name' },
  { field: 'details.middleName', label: 'Middle Name' },
] as const;
