export const FORM_TOGGLE = 'FORM_TOGGLE';
export const CONVERSATION_SENT = 'CONVERSATION_SENT';
export const EMAIL_LOCAL_STORAGE_KEY = 'erxesChatWidgetEmail';
export const NEW_CONVERSATION = 'NEW_CONVERSATION';
export const STATUS_CHANGED = 'STATUS_CHANGED';
