export const menuDynamic = [
  { title: 'Sync History', link: '/sync-msdynamic-history' },
  { title: 'Check orders', link: '/check-sync-orders' },
  { title: 'Check Categories', link: '/msdynamic-category' },
  { title: 'Check Products', link: '/msdynamic-products' },
  { title: 'Check Price', link: '/msdynamic-price' },
  { title: 'Check Customers', link: '/msdynamic-customers' },
];

export const KEY_LABELS: Record<string, string> = {
  brandId: 'brand',
  itemApi: 'item-api',
  itemCategoryApi: 'item-category-api',
  priceApi: 'price-api',
  pricePriority: 'price-priority',
  customerApi: 'customer-api',
  salesApi: 'sales-api',
  salesLineApi: 'sales-line-api',
  exchangeRateApi: 'exchange-rate-api',
  discountSoapApi: 'discount-soap-api',
  username: 'username',
  password: 'password',
  genBusPostingGroup: 'gen-bus-posting-group',
  vatBusPostingGroup: 'vat-bus-posting-group',
  customerPostingGroup: 'customer-posting-group',
  customerPricingGroup: 'customer-pricing-group',
  customerDiscGroup: 'customer-disc-group',
  paymentTermsCode: 'payment-terms-code',
  paymentMethodCode: 'payment-method-code',
  reminderCode: 'location-code-remainder',
  locationCode: 'location-code-sale',
  responsibilityCenter: 'responsibility-center',
  billType: 'bill-type',
  dealType: 'deal-type-code',
  syncType: 'sync-type',
  defaultUserCode: 'default-user-code',
  defaultCompanyCode: 'default-company-code',
  useBoard: 'use-deal-board',
  boardId: 'board',
  pipelineId: 'pipeline',
  stageId: 'stage',
  posConf: 'pos-config',
  productUrl: 'product-url',
  custCode: 'cust-code',
  userLocationCode: 'user-location-code',
};
