import { IReportConfig } from './common';

export const mainReportRules: Record<string, IReportConfig> = {
  ac: {
    title: 'account-statement',
    colCount: 6,
    choices: [
      { code: 'default', title: 'by-account' },
      { code: 'cat', title: 'by-account-category' },
      { code: 'branchDepartment', title: 'by-branch-and-department' },
      { code: 'departmentBranch', title: 'by-department-and-branch' },
    ],
    groups: {
      default: {
        group: 'accountId',
        code: 'accountCode',
        name: 'accountName',
        from: ['details'],
        style: 'font-semibold bg-[#fefef1]',
        groupRule: null,
      },
      cat: {
        group: 'accountCategoryId',
        code: 'accountCategoryCode',
        name: 'accountCategoryName',
        excMore: true,
        style: 'font-semibold',
        groupRule: {
          group: 'accountId',
          code: 'accountCode',
          name: 'accountName',
          from: ['details'],
          style: 'font-semibold bg-[#fefef1]',
          groupRule: null,
        },
      },
      branchDepartment: {
        group: 'branchId',
        code: 'branchCode',
        name: 'branchName',
        style: 'font-semibold',
        groupRule: {
          group: 'departmentId',
          code: 'departmentCode',
          name: 'departmentName',
          style: 'font-semibold',
          groupRule: {
            group: 'accountId',
            code: 'accountCode',
            name: 'accountName',
            from: ['details'],
            style: 'font-semibold bg-[#fefef1]',
            groupRule: null,
          },
        },
      },
      departmentBranch: {
        group: 'departmentId',
        code: 'departmentCode',
        name: 'departmentName',
        style: 'font-semibold',
        groupRule: {
          group: 'branchId',
          code: 'branchCode',
          name: 'branchName',
          style: 'font-semibold',
          groupRule: {
            group: 'accountId',
            code: 'accountCode',
            name: 'accountName',
            from: ['details'],
            style: 'font-semibold bg-[#fefef1]',
            groupRule: null,
          },
        },
      },
    },
  },
  tb: {
    title: 'trial-balance',
    colCount: 6,
    choices: [
      { code: 'default', title: 'by-account' },
      { code: 'cat', title: 'by-account-category' },
      { code: 'branchDepartment', title: 'by-branch-and-department' },
      { code: 'departmentBranch', title: 'by-department-and-branch' },
    ],
    groups: {
      default: {
        group: 'accountId',
        code: 'accountCode',
        name: 'accountName',
        from: ['details'],
        groupRule: null,
      },
      cat: {
        group: 'accountCategoryId',
        code: 'accountCategoryCode',
        name: 'accountCategoryName',
        style: 'font-semibold',
        groupRule: {
          group: 'accountId',
          code: 'accountCode',
          name: 'accountName',
          groupRule: null,
        },
      },
      branchDepartment: {
        group: 'branchId',
        code: 'branchCode',
        name: 'branchName',
        style: 'font-semibold',
        groupRule: {
          group: 'departmentId',
          code: 'departmentCode',
          name: 'departmentName',
          style: 'font-semibold',
          groupRule: {
            group: 'accountId',
            code: 'accountCode',
            name: 'accountName',
            from: ['details'],
            style: '',
            groupRule: null,
          },
        },
      },
      departmentBranch: {
        group: 'departmentId',
        code: 'departmentCode',
        name: 'departmentName',
        style: 'font-semibold',
        groupRule: {
          group: 'branchId',
          code: 'branchCode',
          name: 'branchName',
          style: 'font-semibold',
          groupRule: {
            group: 'accountId',
            code: 'accountCode',
            name: 'accountName',
            from: ['details'],
            style: '',
            groupRule: null,
          },
        },
      },
    },
  },
  mb: {
    title: 'general-ledger',
    colCount: 6,
    choices: [
      { code: 'default', title: 'by-account' },
      { code: 'cat', title: 'by-account-category' },
    ],
    groups: {
      default: {
        group: 'accountId',
        code: 'accountCode',
        name: 'accountName',
        from: ['details'],
        style: 'font-semibold bg-[#fefef1]',
        groupRule: null,
      },
      cat: {
        group: 'accountCategoryId',
        code: 'accountCategoryCode',
        name: 'accountCategoryName',
        excMore: true,
        style: 'font-semibold',
        groupRule: {
          group: 'accountId',
          code: 'accountCode',
          name: 'accountName',
          from: ['details'],
          style: 'font-semibold bg-[#fefef1]',
          groupRule: null,
        },
      },
    },
  },
  mj: {
    title: 'general-journal',
    colCount: 2,
    groups: {
      default: {
        group: 'ptrId',
        code: 'date',
        name: 'description',
        style: 'font-semibold',
        groupRule: {
          group: 'accountId',
          code: 'accountCode',
          name: 'accountName',
          groupRule: null,
        },
      },
    },
  },
  mjs: {
    title: 'general-journal-summary',
    colCount: 5,
    groups: {
      default: {
        group: 'ptrId',
        code: 'date',
        name: 'number',
        groupRule: null,
      },
    },
  },
};
