import type { TablerIcon } from '@tabler/icons-react';
import {
  IconAirConditioning,
  IconAirBalloon,
  IconAlarmSmoke,
  IconBabyBottle,
  IconBabyCarriage,
  IconBackpack,
  IconBallFootball,
  IconBallTennis,
  IconBalloon,
  IconBarbell,
  IconBath,
  IconBinoculars,
  IconBrandBooking,
  IconBrandInstagram,
  IconBrandTelegram,
  IconBrandWhatsapp,
  IconBus,
  IconCloudRain,
  IconCloudSnow,
  IconCoffee,
  IconCompass,
  IconDeviceLaptop,
  IconDeviceMobile,
  IconDeviceTablet,
  IconDeviceTv,
  IconDisabled,
  IconDroplet,
  IconFlower,
  IconFridge,
  IconGift,
  IconGlassFull,
  IconHeadphones,
  IconMapPin,
  IconMapSearch,
  IconMassage,
  IconMeat,
  IconMicrowave,
  IconMicrophone,
  IconMoonStars,
  IconMovie,
  IconMotorbike,
  IconMug,
  IconMusic,
  IconNavigation,
  IconPalette,
  IconParking,
  IconPaw,
  IconPhoneCalling,
  IconPhoto,
  IconPlane,
  IconPlayCard,
  IconPlug,
  IconPool,
  IconPuzzle2,
  IconQrcode,
  IconReceipt,
  IconRoute,
  IconRouter,
  IconRun,
  IconSalad,
  IconShieldCheck,
  IconShoppingBag,
  IconSun,
  IconSunrise,
  IconSunset,
  IconSwimming,
  IconTent,
  IconTicket,
  IconToiletPaper,
  IconTrees,
  IconUmbrella,
  IconUsersGroup,
  IconVideo,
  IconWalk,
  IconWashMachine,
  IconWifi,
  IconWind,
  IconChefHat,
  IconToolsKitchen2,
  IconIroning3,
  IconHanger,
  IconSnowflake,
  IconFlame,
  IconSmoking,
  IconSmokingNo,
  IconBellRinging,
  IconKey,
  IconCar,
  IconFirstAidKit,
  IconLifebuoy,
  IconMountain,
  IconBeach,
  IconDog,
  IconCat,
  IconFriends,
  IconElevator,
  IconWindmill,
  IconCactus,
  IconEgg,
  IconPizza,
  IconSoup,
  IconCoffeeOff,
  IconBeer,
  IconBottle,
  IconCarrot,
  IconCheese,
  IconFish,
  IconIceCream,
  IconLemon2,
} from '@tabler/icons-react';

export interface IAmenityIconOption {
  name: string;
  label: string;
  keywords: string[];
  icon: TablerIcon;
}

export const AMENITY_ICON_OPTIONS: IAmenityIconOption[] = [
  {
    name: 'IconWifi',
    label: 'Wi-Fi',
    keywords: ['internet', 'wireless', 'network'],
    icon: IconWifi,
  },
  {
    name: 'IconAirConditioning',
    label: 'Air Conditioning',
    keywords: ['ac', 'cooling', 'climate'],
    icon: IconAirConditioning,
  },
  {
    name: 'IconBath',
    label: 'Private Bathroom',
    keywords: ['bathroom', 'shower', 'toilet'],
    icon: IconBath,
  },
  {
    name: 'IconPool',
    label: 'Pool',
    keywords: ['swimming', 'water', 'leisure'],
    icon: IconPool,
  },
  {
    name: 'IconSwimming',
    label: 'Swimming',
    keywords: ['pool', 'water', 'sport'],
    icon: IconSwimming,
  },
  {
    name: 'IconParking',
    label: 'Parking',
    keywords: ['car', 'vehicle', 'garage'],
    icon: IconParking,
  },
  {
    name: 'IconCoffee',
    label: 'Breakfast',
    keywords: ['coffee', 'meal', 'cafe'],
    icon: IconCoffee,
  },
  {
    name: 'IconMug',
    label: 'Hot Drinks',
    keywords: ['tea', 'coffee', 'beverage'],
    icon: IconMug,
  },
  {
    name: 'IconMeat',
    label: 'Restaurant',
    keywords: ['food', 'dining', 'bbq'],
    icon: IconMeat,
  },
  {
    name: 'IconSalad',
    label: 'Healthy Food',
    keywords: ['food', 'vegan', 'meal'],
    icon: IconSalad,
  },
  {
    name: 'IconFridge',
    label: 'Mini Fridge',
    keywords: ['cooler', 'kitchen', 'appliance'],
    icon: IconFridge,
  },
  {
    name: 'IconMicrowave',
    label: 'Microwave',
    keywords: ['kitchen', 'food', 'appliance'],
    icon: IconMicrowave,
  },
  {
    name: 'IconGlassFull',
    label: 'Bar',
    keywords: ['drink', 'cocktail', 'beverage'],
    icon: IconGlassFull,
  },
  {
    name: 'IconDeviceTv',
    label: 'TV',
    keywords: ['screen', 'media', 'entertainment'],
    icon: IconDeviceTv,
  },
  {
    name: 'IconVideo',
    label: 'Streaming',
    keywords: ['video', 'media', 'screen'],
    icon: IconVideo,
  },
  {
    name: 'IconMoonStars',
    label: 'Night Stay',
    keywords: ['sleep', 'room', 'overnight'],
    icon: IconMoonStars,
  },
  {
    name: 'IconShieldCheck',
    label: 'Security',
    keywords: ['safe', 'protected', 'guard'],
    icon: IconShieldCheck,
  },
  {
    name: 'IconAlarmSmoke',
    label: 'Smoke Alarm',
    keywords: ['safety', 'fire', 'alarm'],
    icon: IconAlarmSmoke,
  },
  {
    name: 'IconDisabled',
    label: 'Accessible',
    keywords: ['wheelchair', 'barrier free', 'inclusive'],
    icon: IconDisabled,
  },
  {
    name: 'IconBabyCarriage',
    label: 'Family Friendly',
    keywords: ['baby', 'stroller', 'kids'],
    icon: IconBabyCarriage,
  },
  {
    name: 'IconPaw',
    label: 'Pet Friendly',
    keywords: ['pets', 'dog', 'cat'],
    icon: IconPaw,
  },
  {
    name: 'IconMassage',
    label: 'Massage',
    keywords: ['spa', 'wellness', 'relax'],
    icon: IconMassage,
  },
  {
    name: 'IconDroplet',
    label: 'Spa',
    keywords: ['wellness', 'water', 'relax'],
    icon: IconDroplet,
  },
  {
    name: 'IconUmbrella',
    label: 'Beach Umbrella',
    keywords: ['shade', 'outdoor', 'beach'],
    icon: IconUmbrella,
  },
  {
    name: 'IconWind',
    label: 'Windy View',
    keywords: ['weather', 'breeze', 'outdoor'],
    icon: IconWind,
  },
  {
    name: 'IconCloudRain',
    label: 'Rainy Season',
    keywords: ['weather', 'rain', 'forecast'],
    icon: IconCloudRain,
  },
  {
    name: 'IconCloudSnow',
    label: 'Snow Activity',
    keywords: ['weather', 'winter', 'snow'],
    icon: IconCloudSnow,
  },
  {
    name: 'IconSunrise',
    label: 'Sunrise View',
    keywords: ['morning', 'view', 'nature'],
    icon: IconSunrise,
  },
  {
    name: 'IconSunset',
    label: 'Sunset View',
    keywords: ['evening', 'view', 'nature'],
    icon: IconSunset,
  },
  {
    name: 'IconSun',
    label: 'Sunny Spot',
    keywords: ['daylight', 'sunny', 'outdoor'],
    icon: IconSun,
  },
  {
    name: 'IconFlower',
    label: 'Garden',
    keywords: ['flowers', 'nature', 'park'],
    icon: IconFlower,
  },
  {
    name: 'IconTrees',
    label: 'Forest View',
    keywords: ['trees', 'nature', 'green'],
    icon: IconTrees,
  },
  {
    name: 'IconTent',
    label: 'Camping',
    keywords: ['outdoor', 'camp', 'nature'],
    icon: IconTent,
  },
  {
    name: 'IconAirBalloon',
    label: 'Balloon Tour',
    keywords: ['adventure', 'sky', 'tour'],
    icon: IconAirBalloon,
  },
  {
    name: 'IconBackpack',
    label: 'Hiking',
    keywords: ['trek', 'travel', 'outdoor'],
    icon: IconBackpack,
  },
  {
    name: 'IconBinoculars',
    label: 'Sightseeing',
    keywords: ['view', 'watching', 'tour'],
    icon: IconBinoculars,
  },
  {
    name: 'IconCompass',
    label: 'Explorer',
    keywords: ['direction', 'adventure', 'tour'],
    icon: IconCompass,
  },
  {
    name: 'IconNavigation',
    label: 'Navigation',
    keywords: ['route', 'map', 'gps'],
    icon: IconNavigation,
  },
  {
    name: 'IconRoute',
    label: 'Road Trip',
    keywords: ['route', 'travel', 'drive'],
    icon: IconRoute,
  },
  {
    name: 'IconMapPin',
    label: 'Location',
    keywords: ['map', 'place', 'pin'],
    icon: IconMapPin,
  },
  {
    name: 'IconPlane',
    label: 'Airport Transfer',
    keywords: ['flight', 'travel', 'pickup'],
    icon: IconPlane,
  },
  {
    name: 'IconBus',
    label: 'Bus Access',
    keywords: ['transport', 'shuttle', 'travel'],
    icon: IconBus,
  },
  {
    name: 'IconMotorbike',
    label: 'Bike Rental',
    keywords: ['motorbike', 'scooter', 'ride'],
    icon: IconMotorbike,
  },
  {
    name: 'IconRun',
    label: 'Running',
    keywords: ['fitness', 'sport', 'activity'],
    icon: IconRun,
  },
  {
    name: 'IconWalk',
    label: 'Walking Tour',
    keywords: ['hike', 'walk', 'activity'],
    icon: IconWalk,
  },
  {
    name: 'IconBarbell',
    label: 'Gym',
    keywords: ['fitness', 'workout', 'sport'],
    icon: IconBarbell,
  },
  {
    name: 'IconBallFootball',
    label: 'Football',
    keywords: ['soccer', 'sport', 'play'],
    icon: IconBallFootball,
  },
  {
    name: 'IconBallTennis',
    label: 'Tennis',
    keywords: ['sport', 'court', 'play'],
    icon: IconBallTennis,
  },
  {
    name: 'IconBalloon',
    label: 'Kids Play',
    keywords: ['children', 'family', 'fun'],
    icon: IconBalloon,
  },
  {
    name: 'IconBabyBottle',
    label: 'Baby Care',
    keywords: ['family', 'infant', 'child'],
    icon: IconBabyBottle,
  },
  {
    name: 'IconPlayCard',
    label: 'Game Room',
    keywords: ['cards', 'game', 'fun'],
    icon: IconPlayCard,
  },
  {
    name: 'IconPuzzle2',
    label: 'Kids Activities',
    keywords: ['puzzle', 'family', 'play'],
    icon: IconPuzzle2,
  },
  {
    name: 'IconDeviceLaptop',
    label: 'Workspace',
    keywords: ['work', 'desk', 'business'],
    icon: IconDeviceLaptop,
  },
  {
    name: 'IconDeviceTablet',
    label: 'Tablet Access',
    keywords: ['device', 'screen', 'digital'],
    icon: IconDeviceTablet,
  },
  {
    name: 'IconDeviceMobile',
    label: 'Mobile Friendly',
    keywords: ['phone', 'digital', 'app'],
    icon: IconDeviceMobile,
  },
  {
    name: 'IconRouter',
    label: 'Strong Network',
    keywords: ['internet', 'router', 'wifi'],
    icon: IconRouter,
  },
  {
    name: 'IconPlug',
    label: 'Power Outlet',
    keywords: ['electricity', 'charge', 'socket'],
    icon: IconPlug,
  },
  {
    name: 'IconWashMachine',
    label: 'Laundry',
    keywords: ['washing', 'cleaning', 'washer'],
    icon: IconWashMachine,
  },
  {
    name: 'IconToiletPaper',
    label: 'Toiletries',
    keywords: ['bathroom', 'supplies', 'comfort'],
    icon: IconToiletPaper,
  },
  {
    name: 'IconPhoneCalling',
    label: 'Call Service',
    keywords: ['phone', 'contact', 'support'],
    icon: IconPhoneCalling,
  },
  {
    name: 'IconBrandWhatsapp',
    label: 'WhatsApp Support',
    keywords: ['chat', 'support', 'message'],
    icon: IconBrandWhatsapp,
  },
  {
    name: 'IconBrandTelegram',
    label: 'Telegram Support',
    keywords: ['chat', 'support', 'message'],
    icon: IconBrandTelegram,
  },
  {
    name: 'IconBrandInstagram',
    label: 'Instagram',
    keywords: ['social', 'media', 'photo'],
    icon: IconBrandInstagram,
  },
  {
    name: 'IconBrandBooking',
    label: 'Booking',
    keywords: ['reservation', 'travel', 'platform'],
    icon: IconBrandBooking,
  },
  {
    name: 'IconTicket',
    label: 'Ticketing',
    keywords: ['entry', 'booking', 'pass'],
    icon: IconTicket,
  },
  {
    name: 'IconQrcode',
    label: 'QR Check-in',
    keywords: ['scan', 'digital', 'entry'],
    icon: IconQrcode,
  },
  {
    name: 'IconReceipt',
    label: 'Invoice',
    keywords: ['bill', 'payment', 'receipt'],
    icon: IconReceipt,
  },
  {
    name: 'IconShoppingBag',
    label: 'Gift Shop',
    keywords: ['shop', 'store', 'souvenir'],
    icon: IconShoppingBag,
  },
  {
    name: 'IconGift',
    label: 'Welcome Gift',
    keywords: ['present', 'gift', 'bonus'],
    icon: IconGift,
  },
  {
    name: 'IconPalette',
    label: 'Art Space',
    keywords: ['creative', 'art', 'studio'],
    icon: IconPalette,
  },
  {
    name: 'IconMusic',
    label: 'Live Music',
    keywords: ['entertainment', 'audio', 'event'],
    icon: IconMusic,
  },
  {
    name: 'IconMovie',
    label: 'Cinema',
    keywords: ['movie', 'entertainment', 'screen'],
    icon: IconMovie,
  },
  {
    name: 'IconMicrophone',
    label: 'Karaoke',
    keywords: ['singing', 'audio', 'event'],
    icon: IconMicrophone,
  },
  {
    name: 'IconHeadphones',
    label: 'Audio Guide',
    keywords: ['music', 'sound', 'guide'],
    icon: IconHeadphones,
  },
  {
    name: 'IconPhoto',
    label: 'Photo Spot',
    keywords: ['camera', 'picture', 'view'],
    icon: IconPhoto,
  },
  {
    name: 'IconMapSearch',
    label: 'Nearby Attractions',
    keywords: ['map', 'discover', 'attraction'],
    icon: IconMapSearch,
  },
  {
    name: 'IconUsersGroup',
    label: 'Group Friendly',
    keywords: ['team', 'group', 'family'],
    icon: IconUsersGroup,
  },
  {
    name: 'IconToolsKitchen2',
    label: 'Kitchenette',
    keywords: ['cooking', 'stove', 'kitchen'],
    icon: IconToolsKitchen2,
  },
  {
    name: 'IconChefHat',
    label: 'Professional Chef',
    keywords: ['food', 'restaurant', 'dining'],
    icon: IconChefHat,
  },
  {
    name: 'IconIroning3',
    label: 'Ironing',
    keywords: ['iron', 'laundry', 'clothes'],
    icon: IconIroning3,
  },
  {
    name: 'IconHanger',
    label: 'Wardrobe',
    keywords: ['closet', 'clothes', 'storage'],
    icon: IconHanger,
  },
  {
    name: 'IconSnowflake',
    label: 'Heating / Cooling',
    keywords: ['winter', 'climate', 'ac'],
    icon: IconSnowflake,
  },
  {
    name: 'IconFlame',
    label: 'Fireplace',
    keywords: ['heat', 'warm', 'cozy'],
    icon: IconFlame,
  },
  {
    name: 'IconSmoking',
    label: 'Smoking Area',
    keywords: ['smoke', 'cigarette', 'allowed'],
    icon: IconSmoking,
  },
  {
    name: 'IconSmokingNo',
    label: 'Non-smoking',
    keywords: ['smoke', 'no smoking', 'clean air'],
    icon: IconSmokingNo,
  },
  {
    name: 'IconElevator',
    label: 'Elevator',
    keywords: ['lift', 'stairs', 'floor'],
    icon: IconElevator,
  },
  {
    name: 'IconBellRinging',
    label: 'Reception 24/7',
    keywords: ['lobby', 'service', 'front desk'],
    icon: IconBellRinging,
  },
  {
    name: 'IconKey',
    label: 'Private Entrance',
    keywords: ['access', 'security', 'door'],
    icon: IconKey,
  },
  {
    name: 'IconCar',
    label: 'Car Rental',
    keywords: ['auto', 'transport', 'vehicle'],
    icon: IconCar,
  },
  {
    name: 'IconMountain',
    label: 'Mountain View',
    keywords: ['nature', 'hiking', 'scenery'],
    icon: IconMountain,
  },
  {
    name: 'IconBeach',
    label: 'Beach Access',
    keywords: ['sea', 'ocean', 'sand'],
    icon: IconBeach,
  },
  {
    name: 'IconFirstAidKit',
    label: 'First Aid',
    keywords: ['medical', 'safety', 'health'],
    icon: IconFirstAidKit,
  },
  {
    name: 'IconLifebuoy',
    label: 'Water Safety',
    keywords: ['pool', 'sea', 'rescue'],
    icon: IconLifebuoy,
  },
  {
    name: 'IconEgg',
    label: 'Breakfast Included',
    keywords: ['morning', 'food', 'egg'],
    icon: IconEgg,
  },
  {
    name: 'IconSoup',
    label: 'Warm Meals',
    keywords: ['soup', 'dinner', 'lunch'],
    icon: IconSoup,
  },
  {
    name: 'IconPizza',
    label: 'Snacks & Pizza',
    keywords: ['fast food', 'junk food', 'pizza'],
    icon: IconPizza,
  },
  {
    name: 'IconCarrot',
    label: 'Vegetarian',
    keywords: ['vegan', 'vegetable', 'healthy'],
    icon: IconCarrot,
  },
  {
    name: 'IconFish',
    label: 'Seafood',
    keywords: ['fish', 'ocean', 'dining'],
    icon: IconFish,
  },
  {
    name: 'IconCheese',
    label: 'Dairy Products',
    keywords: ['cheese', 'milk', 'breakfast'],
    icon: IconCheese,
  },
  {
    name: 'IconBeer',
    label: 'Craft Beer',
    keywords: ['alcohol', 'bar', 'pub'],
    icon: IconBeer,
  },
  {
    name: 'IconBottle',
    label: 'Wine & Spirits',
    keywords: ['alcohol', 'drink', 'bottle'],
    icon: IconBottle,
  },
  {
    name: 'IconCoffeeOff',
    label: 'Caffeine Free',
    keywords: ['tea', 'decaf', 'health'],
    icon: IconCoffeeOff,
  },
  {
    name: 'IconIceCream',
    label: 'Desserts',
    keywords: ['sweet', 'ice cream', 'kids'],
    icon: IconIceCream,
  },
  {
    name: 'IconLemon2',
    label: 'Fresh Juice',
    keywords: ['fruit', 'drink', 'vitamins'],
    icon: IconLemon2,
  },
  {
    name: 'IconDog',
    label: 'Dog Friendly',
    keywords: ['pets', 'animals', 'dog allowed'],
    icon: IconDog,
  },
  {
    name: 'IconCat',
    label: 'Cat Friendly',
    keywords: ['pets', 'animals', 'cat allowed'],
    icon: IconCat,
  },
  {
    name: 'IconFriends',
    label: 'Social Space',
    keywords: ['group', 'friends', 'community', 'common area'],
    icon: IconFriends,
  },
  {
    name: 'IconCactus',
    label: 'Desert / Garden',
    keywords: ['nature', 'dry climate', 'scenery', 'outdoor'],
    icon: IconCactus,
  },
  {
    name: 'IconWindmill',
    label: 'Eco Energy',
    keywords: ['wind', 'sustainable', 'farm', 'nature'],
    icon: IconWindmill,
  },
];

export const getAmenityIconOption = (name?: string | null) => {
  if (!name) {
    return null;
  }

  return AMENITY_ICON_OPTIONS.find((option) => option.name === name) ?? null;
};
