version: "3"
services:
  mongo:
    hostname: mongo
    image: mongo:4.0.20
    container_name: mongo
    ports:
      - "127.0.0.1:27017:27017"
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 2s
      timeout: 2s
      retries: 200
    command: ["--replSet", "rs0", "--bind_ip_all"]
    # All erxes database will be saved into mounted directory below. <<IF YOU DELETE THIS MOUNTED DIRECTORY ALL OF YOUR ERXES DATA WILL BE LOST SO BE CAUTIOUS>>
    volumes:
      - ./data/db:/data/db
    networks:
      - erxes-net

  redis:
    image: "redis"
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - erxes-net

  rabbitmq:
    image: rabbitmq:3.7.17-management
    container_name: rabbitmq
    restart: unless-stopped
    hostname: rabbitmq
    ports:
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:5672:5672"
    networks:
      - erxes-net
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.13.0-arm64"
    container_name: "elasticsearch"
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 32768
        hard: 65536
    ports:
      - "127.0.0.1:9200:9200"
    networks:
      - erxes-net
    volumes:
      - ./elasticsearchData:/usr/share/elasticsearch/data

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.13.0-arm64"
    container_name: "kibana"
    depends_on:
      - "elasticsearch"
    ports:
      - "127.0.0.1:5601:5601"
    networks:
      - erxes-net

  essyncer:
    container_name: essyncer
    image: "erxes/essyncer:dev"
    environment:
      DB_NAME: "erxes"
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      MONGO_URL: "mongodb://mongo:27017/erxes?replicaSet=rs0"
    depends_on:
      - "mongo"
      - "elasticsearch"
    volumes:
      - "./essyncerData:/data/essyncerData"
    tty: true
    networks:
      - "erxes-net"

  client-portal:
    container_name: client-portal
    build:
      context: ../client-portal
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:4200:4200"
    environment:
      API_URL: http://core-api:3100/graphql
      REACT_APP_DOMAIN: http://localhost:4200
      REACT_APP_SUBSCRIPTION_URL: ws://core-api:3100/graphql
    depends_on:
      - core-api
    networks:
      - erxes-net

  core-api:
    container_name: core-api
    build:
      context: ../packages/core
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3100:3100"
    environment:
      NODE_ENV: development
      PORT: 3100
      MONGO_URL: mongodb://mongo:27017/erxes?replicaSet=rs0
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOSTNAME: rabbitmq
      DOMAIN: http://localhost:4200
      MAIN_APP_DOMAIN: http://localhost:4200
      CLIENT_PORTAL_DOMAINS: http://localhost:4200
      JWT_TOKEN_SECRET: "some-secret-key" # Please change this in a real environment
      ENABLED_SERVICES_JSON: '{"core": true}'
    depends_on:
      - mongo
      - redis
      - rabbitmq
    networks:
      - erxes-net

networks:
  erxes-net:
    driver: bridge
