export const TEXT_COLORS = [
  '#fff',
  '#fefefe',
  '#fafafa',
  '#ccc',
  '#ddd',
  '#888',
  '#444',
  '#333',
  '#222',
  '#000'
];

export const DISTRICTS = [
  { value: '01', label: 'Архангай' },
  { value: '02', label: 'Баян-Өлгий' },
  { value: '03', label: 'Баянхонгор' },
  { value: '04', label: 'Булган' },
  { value: '05', label: 'Говь-Алтай' },
  { value: '06', label: 'Дорноговь' },
  { value: '07', label: 'Дорнод' },
  { value: '08', label: 'Дундговь' },
  { value: '09', label: 'Завхан' },
  { value: '10', label: 'Өвөрхангай' },
  { value: '11', label: 'Өмнөговь' },
  { value: '12', label: 'Сүхбаатар аймаг' },
  { value: '13', label: 'Сэлэнгэ' },
  { value: '14', label: 'Төв' },
  { value: '15', label: 'Увс' },
  { value: '16', label: 'Ховд' },
  { value: '17', label: 'Хөвсгөл' },
  { value: '18', label: 'Хэнтий' },
  { value: '19', label: 'Дархан-Уул' },
  { value: '20', label: 'Орхон' },
  { value: '32', label: 'Говьсүмбэр' },
  { value: '23', label: 'Хан-Уул' },
  { value: '24', label: 'Баянзүрх' },
  { value: '25', label: 'Сүхбаатар' },
  { value: '26', label: 'Баянгол' },
  { value: '27', label: 'Багануур' },
  { value: '28', label: 'Багахангай' },
  { value: '29', label: 'Налайх' },
  { value: '34', label: 'Сонгинохайрхан' },
  { value: '35', label: 'Чингэлтэй' }
];

export const FILTER_PARAMS = [
  'search',
  'customerId',
  'billType',
  'registerNumber',
  'type',
  'createdStartDate',
  'createdEndDate',
  'paidStartDate',
  'paidEndDate',
  'financeStartDate',
  'financeEndDate',
  'paidDate',
  'userId',
  'hasntUser'
];
