import { z } from 'zod';

export const addMSDynamicConfigSchema = z.object({
  title: z.string().trim().min(1, 'Title is required'),
  brandId: z.string().trim().min(1, 'Brand ID is required'),
  itemApi: z.string(),
  itemCategoryApi: z.string(),
  pricePriority: z.string(),
  priceApi: z.string(),
  customerApi: z.string(),
  salesApi: z.string(),
  salesLineApi: z.string(),
  exchangeRateApi: z.string(),
  username: z.string(),
  password: z.string(),
  genBusPostingGroup: z.string(),
  vatBusPostingGroup: z.string(),
  paymentTermsCode: z.string(),
  paymentMethodCode: z.string(),
  customerPostingGroup: z.string(),
  customerPricingGroup: z.string(),
  customerDiscGroup: z.string(),
  locationCode: z.string(),
  reminderCode: z.string(),
  responsibilityCenter: z.string(),
  billType: z.string(),
  dealType: z.string(),
  syncType: z.string(),
  defaultUserCode: z.string(),
  defaultCompanyCode: z.string(),
  useBoard: z.boolean(),
  boardId: z.string(),
  pipelineId: z.string(),
  stageId: z.string(),
  posConf: z.string(),
  productUrl: z.string(),
});
