
import { IContext } from "@erxes/api-utils/src/types"
import { generateModels } from "../../connectionResolver";
const burenscoringMutations = {
  /**
   * Creates a new burenscoring
   */ 
  async burenscoringsAdd(subdomain, doc, _context: IContext) {

    const models = await generateModels(subdomain);
    const defauldValue = {
      "externalScoringResponse": {
          "data": {
              "uuid": "261b0dbe-793c-46ba-9eda-d2e3c233151e",
              "requestId": "Fkh1kZqHq3TtDqofG3GIp",
              "detail": {
                  "creditScore": {
                      "scoringResult": 559,
                      "badRatio": 0.0439,
                      "odds": 20.0
                  },
                  "creditSummary": {
                      "monthlyLoanRepayment": {
                          "userMonthlyRepayment": 0,
                          "lineTotalBaseAmount": 1293400,
                          "lineTotalRemainAmount": 7
                      },
                      "activeLoanInformation": {
                          "activeLoanRemainPercent": 0.0,
                          "activeLoanTotalRemainAmount": 0
                      },
                      "loanClasses": {
                          "outstanding": {
                              "normal": 7,
                              "overdue": 0,
                              "bad": 0,
                              "total": 7
                          },
                          "closed": {
                              "normal": 0,
                              "overdue": 0,
                              "bad": 0,
                              "total": 0
                          },
                          "total": {
                              "normal": 7,
                              "overdue": 0,
                              "bad": 0,
                              "total": 7
                          }
                      },
                      "percentOfOnTimeClosedLoan": null
                  }
              }
          },
          "message": "Success."
      },
      "restInquiryResponse": {
          "customer": {
              "firstname": "bat",
              "lastname": "batin bat",
              "address": null,
              "registerno": "КЪ10111213",
              "familyname": null,
              "nationality": null
          },
          "inquiry": [
              {
                  "ROWNUM": 1,
                  "AA_ORGCODE": null,
                  "AA_LOANCODE": null,
                  "LASTNAME": "batin bat",
                  "CUSTOMERNAME": "bat",
                  "REGISTERNO": "КЪ10111213",
                  "LOANTYPE": "07",
                  "CURRENCYCODE": "MNT",
                  "ADVAMOUNT": 183000.0,
                  "EXPDATE": "2018-08-20",
                  "STARTEDDATE": "2018-08-20",
                  "PAID_DATE": null,
                  "INTERESTINPREC": null,
                  "BALANCE": 1.0,
                  "LOANCLASS": "01",
                  "SUBMRTNAME": [],
                  "STATEREGISTERNO": [],
                  "ORGNAME": "Очир Ундраа ОМЗ ББСБ",
                  "DESCRIPTION": null,
                  "COREGISTERNO": null,
                  "COLASTNAME": null,
                  "COFIRSTNAME": null,
                  "COSTATEREGISTERNO": null,
                  "RELATION_TYPE": "MAIN",
                  "SUBMRT": [],
                  "HAS_CORELATION": null,
                  "LOAN_CLASS_CHANGED": null
              },
              {
                  "ROWNUM": 2,
                  "AA_ORGCODE": null,
                  "AA_LOANCODE": null,
                  "LASTNAME": "batin bat",
                  "CUSTOMERNAME": "bat",
                  "REGISTERNO": "КЪ10111213",
                  "LOANTYPE": "07",
                  "CURRENCYCODE": "MNT",
                  "ADVAMOUNT": 183000.0,
                  "EXPDATE": "2018-08-20",
                  "STARTEDDATE": "2023-11-20",
                  "PAID_DATE": null,
                  "INTERESTINPREC": null,
                  "BALANCE": 1.0,
                  "LOANCLASS": "01",
                  "SUBMRTNAME": [],
                  "STATEREGISTERNO": [],
                  "ORGNAME": "Очир Ундраа ОМЗ ББСБ",
                  "DESCRIPTION": null,
                  "COREGISTERNO": null,
                  "COLASTNAME": null,
                  "COFIRSTNAME": null,
                  "COSTATEREGISTERNO": null,
                  "RELATION_TYPE": "MAIN",
                  "SUBMRT": [],
                  "HAS_CORELATION": null,
                  "LOAN_CLASS_CHANGED": null
              },
              {
                  "ROWNUM": 3,
                  "AA_ORGCODE": null,
                  "AA_LOANCODE": null,
                  "LASTNAME": "batin bat",
                  "CUSTOMERNAME": "bat",
                  "REGISTERNO": "КЪ10111213",
                  "LOANTYPE": "07",
                  "CURRENCYCODE": "MNT",
                  "ADVAMOUNT": 183000.0,
                  "EXPDATE": "2018-08-20",
                  "STARTEDDATE": "2023-11-20",
                  "PAID_DATE": null,
                  "INTERESTINPREC": null,
                  "BALANCE": 1.0,
                  "LOANCLASS": "01",
                  "SUBMRTNAME": [],
                  "STATEREGISTERNO": [],
                  "ORGNAME": "Очир Ундраа ОМЗ ББСБ",
                  "DESCRIPTION": null,
                  "COREGISTERNO": null,
                  "COLASTNAME": null,
                  "COFIRSTNAME": null,
                  "COSTATEREGISTERNO": null,
                  "RELATION_TYPE": "MAIN",
                  "SUBMRT": [],
                  "HAS_CORELATION": null,
                  "LOAN_CLASS_CHANGED": null
              },
              {
                  "ROWNUM": 4,
                  "AA_ORGCODE": null,
                  "AA_LOANCODE": null,
                  "LASTNAME": "batin bat",
                  "CUSTOMERNAME": "bat",
                  "REGISTERNO": "КЪ10111213",
                  "LOANTYPE": "07",
                  "CURRENCYCODE": "MNT",
                  "ADVAMOUNT": 185000.0,
                  "EXPDATE": "2018-08-21",
                  "STARTEDDATE": "2023-11-22",
                  "PAID_DATE": null,
                  "INTERESTINPREC": null,
                  "BALANCE": 1.0,
                  "LOANCLASS": "01",
                  "SUBMRTNAME": [],
                  "STATEREGISTERNO": [],
                  "ORGNAME": "Очир Ундраа ОМЗ ББСБ",
                  "DESCRIPTION": null,
                  "COREGISTERNO": null,
                  "COLASTNAME": null,
                  "COFIRSTNAME": null,
                  "COSTATEREGISTERNO": null,
                  "RELATION_TYPE": "MAIN",
                  "SUBMRT": [],
                  "HAS_CORELATION": null,
                  "LOAN_CLASS_CHANGED": null
              },
              {
                  "ROWNUM": 5,
                  "AA_ORGCODE": null,
                  "AA_LOANCODE": null,
                  "LASTNAME": "batin bat",
                  "CUSTOMERNAME": "bat",
                  "REGISTERNO": "КЪ10111213",
                  "LOANTYPE": "03",
                  "CURRENCYCODE": "MNT",
                  "ADVAMOUNT": 183000.0,
                  "EXPDATE": "2018-08-20",
                  "STARTEDDATE": "2023-11-20",
                  "PAID_DATE": null,
                  "INTERESTINPREC": null,
                  "BALANCE": 10.0,
                  "LOANCLASS": null,
                  "SUBMRTNAME": [],
                  "STATEREGISTERNO": [],
                  "ORGNAME": "Очир Ундраа ОМЗ ББСБ",
                  "DESCRIPTION": null,
                  "COREGISTERNO": null,
                  "COLASTNAME": null,
                  "COFIRSTNAME": null,
                  "COSTATEREGISTERNO": null,
                  "RELATION_TYPE": "MAIN",
                  "SUBMRT": [],
                  "HAS_CORELATION": null,
                  "LOAN_CLASS_CHANGED": null
              },
              {
                  "ROWNUM": 6,
                  "AA_ORGCODE": null,
                  "AA_LOANCODE": null,
                  "LASTNAME": "batin bat",
                  "CUSTOMERNAME": "bat",
                  "REGISTERNO": "КЪ10111213",
                  "LOANTYPE": "07",
                  "CURRENCYCODE": "MNT",
                  "ADVAMOUNT": 183000.0,
                  "EXPDATE": "2018-08-20",
                  "STARTEDDATE": "2021-11-20",
                  "PAID_DATE": null,
                  "INTERESTINPREC": null,
                  "BALANCE": 1.0,
                  "LOANCLASS": "01",
                  "SUBMRTNAME": [],
                  "STATEREGISTERNO": [],
                  "ORGNAME": "Очир Ундраа ОМЗ ББСБ",
                  "DESCRIPTION": null,
                  "COREGISTERNO": null,
                  "COLASTNAME": null,
                  "COFIRSTNAME": null,
                  "COSTATEREGISTERNO": null,
                  "RELATION_TYPE": "MAIN",
                  "SUBMRT": [],
                  "HAS_CORELATION": null,
                  "LOAN_CLASS_CHANGED": null
              },
              {
                  "ROWNUM": 7,
                  "AA_ORGCODE": null,
                  "AA_LOANCODE": null,
                  "LASTNAME": "batin bat",
                  "CUSTOMERNAME": "bat",
                  "REGISTERNO": "КЪ10111213",
                  "LOANTYPE": "07",
                  "CURRENCYCODE": "MNT",
                  "ADVAMOUNT": 185000.0,
                  "EXPDATE": "2018-08-21",
                  "STARTEDDATE": "2021-11-22",
                  "PAID_DATE": null,
                  "INTERESTINPREC": null,
                  "BALANCE": 1.0,
                  "LOANCLASS": "01",
                  "SUBMRTNAME": [],
                  "STATEREGISTERNO": [],
                  "ORGNAME": "Очир Ундраа ОМЗ ББСБ",
                  "DESCRIPTION": null,
                  "COREGISTERNO": null,
                  "COLASTNAME": null,
                  "COFIRSTNAME": null,
                  "COSTATEREGISTERNO": null,
                  "RELATION_TYPE": "MAIN",
                  "SUBMRT": [],
                  "HAS_CORELATION": null,
                  "LOAN_CLASS_CHANGED": null
              },
              {
                  "ROWNUM": 8,
                  "AA_ORGCODE": null,
                  "AA_LOANCODE": null,
                  "LASTNAME": "batin bat",
                  "CUSTOMERNAME": "bat",
                  "REGISTERNO": "КЪ10111213",
                  "LOANTYPE": "03",
                  "CURRENCYCODE": "MNT",
                  "ADVAMOUNT": 183000.0,
                  "EXPDATE": "2018-08-20",
                  "STARTEDDATE": "2021-11-20",
                  "PAID_DATE": null,
                  "INTERESTINPREC": null,
                  "BALANCE": 10.0,
                  "LOANCLASS": null,
                  "SUBMRTNAME": [],
                  "STATEREGISTERNO": [],
                  "ORGNAME": "Очир Ундраа ОМЗ ББСБ",
                  "DESCRIPTION": null,
                  "COREGISTERNO": null,
                  "COLASTNAME": null,
                  "COFIRSTNAME": null,
                  "COSTATEREGISTERNO": null,
                  "RELATION_TYPE": "MAIN",
                  "SUBMRT": [],
                  "HAS_CORELATION": null,
                  "LOAN_CLASS_CHANGED": null
              },
              {
                  "ROWNUM": 9,
                  "AA_ORGCODE": null,
                  "AA_LOANCODE": null,
                  "LASTNAME": "batin bat",
                  "CUSTOMERNAME": "bat",
                  "REGISTERNO": "КЪ10111213",
                  "LOANTYPE": "07",
                  "CURRENCYCODE": "MNT",
                  "ADVAMOUNT": 189400.0,
                  "EXPDATE": "2018-08-20",
                  "STARTEDDATE": "2006-11-20",
                  "PAID_DATE": null,
                  "INTERESTINPREC": null,
                  "BALANCE": 1.0,
                  "LOANCLASS": "01",
                  "SUBMRTNAME": [],
                  "STATEREGISTERNO": [],
                  "ORGNAME": "Очир Ундраа ОМЗ ББСБ",
                  "DESCRIPTION": null,
                  "COREGISTERNO": null,
                  "COLASTNAME": null,
                  "COFIRSTNAME": null,
                  "COSTATEREGISTERNO": null,
                  "RELATION_TYPE": "MAIN",
                  "SUBMRT": [],
                  "HAS_CORELATION": null,
                  "LOAN_CLASS_CHANGED": null
              },
              {
                  "ROWNUM": 10,
                  "AA_ORGCODE": null,
                  "AA_LOANCODE": null,
                  "LASTNAME": "batin bat",
                  "CUSTOMERNAME": "bat",
                  "REGISTERNO": "КЪ10111213",
                  "LOANTYPE": "07",
                  "CURRENCYCODE": "MNT",
                  "ADVAMOUNT": 185000.0,
                  "EXPDATE": "2018-08-21",
                  "STARTEDDATE": "2008-11-22",
                  "PAID_DATE": null,
                  "INTERESTINPREC": null,
                  "BALANCE": 1.0,
                  "LOANCLASS": "01",
                  "SUBMRTNAME": [],
                  "STATEREGISTERNO": [],
                  "ORGNAME": "Очир Ундраа ОМЗ ББСБ",
                  "DESCRIPTION": null,
                  "COREGISTERNO": null,
                  "COLASTNAME": null,
                  "COFIRSTNAME": null,
                  "COSTATEREGISTERNO": null,
                  "RELATION_TYPE": "MAIN",
                  "SUBMRT": [],
                  "HAS_CORELATION": null,
                  "LOAN_CLASS_CHANGED": null
              },
              {
                  "ROWNUM": 11,
                  "AA_ORGCODE": null,
                  "AA_LOANCODE": null,
                  "LASTNAME": "batin bat",
                  "CUSTOMERNAME": "bat",
                  "REGISTERNO": "КЪ10111213",
                  "LOANTYPE": "03",
                  "CURRENCYCODE": "MNT",
                  "ADVAMOUNT": 183000.0,
                  "EXPDATE": "2018-08-20",
                  "STARTEDDATE": "2009-11-20",
                  "PAID_DATE": null,
                  "INTERESTINPREC": null,
                  "BALANCE": 10.0,
                  "LOANCLASS": null,
                  "SUBMRTNAME": [],
                  "STATEREGISTERNO": [],
                  "ORGNAME": "Очир Ундраа ОМЗ ББСБ",
                  "DESCRIPTION": null,
                  "COREGISTERNO": null,
                  "COLASTNAME": null,
                  "COFIRSTNAME": null,
                  "COSTATEREGISTERNO": null,
                  "RELATION_TYPE": "MAIN",
                  "SUBMRT": [],
                  "HAS_CORELATION": null,
                  "LOAN_CLASS_CHANGED": null
              },
              {
                  "ROWNUM": 12,
                  "AA_ORGCODE": null,
                  "AA_LOANCODE": null,
                  "LASTNAME": "batin bat",
                  "CUSTOMERNAME": "bat",
                  "REGISTERNO": "КЪ10111213",
                  "LOANTYPE": "03",
                  "CURRENCYCODE": "MNT",
                  "ADVAMOUNT": 1000000.0,
                  "EXPDATE": "2018-08-20",
                  "STARTEDDATE": "2024-11-20",
                  "PAID_DATE": null,
                  "INTERESTINPREC": null,
                  "BALANCE": 10.0,
                  "LOANCLASS": null,
                  "SUBMRTNAME": [],
                  "STATEREGISTERNO": [],
                  "ORGNAME": "Очир Ундраа ОМЗ ББСБ",
                  "DESCRIPTION": null,
                  "COREGISTERNO": null,
                  "COLASTNAME": null,
                  "COFIRSTNAME": null,
                  "COSTATEREGISTERNO": null,
                  "RELATION_TYPE": "MAIN",
                  "SUBMRT": [],
                  "HAS_CORELATION": null,
                  "LOAN_CLASS_CHANGED": null
              },
              {
                  "ROWNUM": 13,
                  "AA_ORGCODE": null,
                  "AA_LOANCODE": null,
                  "LASTNAME": "batin bat",
                  "CUSTOMERNAME": "bat",
                  "REGISTERNO": "КЪ10111213",
                  "LOANTYPE": "01",
                  "CURRENCYCODE": "MNT",
                  "ADVAMOUNT": 0.0,
                  "EXPDATE": "2024-08-02",
                  "STARTEDDATE": "2015-01-30",
                  "PAID_DATE": null,
                  "INTERESTINPREC": null,
                  "BALANCE": 104391.42,
                  "LOANCLASS": "01",
                  "SUBMRTNAME": [],
                  "STATEREGISTERNO": [],
                  "ORGNAME": "Эй Ай Лаб",
                  "DESCRIPTION": null,
                  "COREGISTERNO": null,
                  "COLASTNAME": null,
                  "COFIRSTNAME": null,
                  "COSTATEREGISTERNO": null,
                  "RELATION_TYPE": "MAIN",
                  "SUBMRT": [],
                  "HAS_CORELATION": null,
                  "LOAN_CLASS_CHANGED": null
              },
              {
                  "ROWNUM": 14,
                  "AA_ORGCODE": null,
                  "AA_LOANCODE": null,
                  "LASTNAME": "batin bat",
                  "CUSTOMERNAME": "bat",
                  "REGISTERNO": "КЪ10111213",
                  "LOANTYPE": "01",
                  "CURRENCYCODE": "MNT",
                  "ADVAMOUNT": 0.0,
                  "EXPDATE": "2024-08-02",
                  "STARTEDDATE": "2015-03-30",
                  "PAID_DATE": "2023-07-03",
                  "INTERESTINPREC": null,
                  "BALANCE": 0.0,
                  "LOANCLASS": "01",
                  "SUBMRTNAME": [],
                  "STATEREGISTERNO": [],
                  "ORGNAME": "Эй Ай Лаб",
                  "DESCRIPTION": null,
                  "COREGISTERNO": null,
                  "COLASTNAME": null,
                  "COFIRSTNAME": null,
                  "COSTATEREGISTERNO": null,
                  "RELATION_TYPE": "MAIN",
                  "SUBMRT": [],
                  "HAS_CORELATION": null,
                  "LOAN_CLASS_CHANGED": null
              }
          ],
          "groupedPurposes": [
              {
                  "count": 1,
                  "purposeCode": 300,
                  "purpose": "CITIZEN_REQUEST",
                  "description": "Иргэний хүсэлтээр"
              },
              {
                  "count": 98,
                  "purposeCode": 500,
                  "purpose": "LOAN",
                  "description": "Зээлийн судалгаа"
              },
              {
                  "count": 97,
                  "purposeCode": 100,
                  "purpose": "NEW_LOAN",
                  "description": "Шинэ зээлийн судалгаа"
              }
          ],
          "histories": [
              {
                  "requester": "Худалдаа хөгжлийн банк",
                  "requestedDate": "2024-04-16 11:40:33",
                  "purpose": "NEW_LOAN"
              },
              {
                  "requester": "Худалдаа хөгжлийн банк",
                  "requestedDate": "2024-04-16 11:18:58",
                  "purpose": "NEW_LOAN"
              },
              {
                  "requester": "Худалдаа хөгжлийн банк",
                  "requestedDate": "2024-04-16 11:18:09",
                  "purpose": "NEW_LOAN"
              }
          ]
      },
      "score": 559
  }
    return await models.BurenScorings.createBurenscoring(defauldValue);

  }
};

export default burenscoringMutations;
