import {
    MainStyleActivityContent as ActivityContent,
    MainStyleBoxRoot as BoxRoot,
    MainStyleButtonRelated as ButtonRelated,
    MainStyleCenterContent as CenterContent,
    MainStyleCloseModal as CloseModal,
    MainStyleCount as Count,
    MainStyleDateContainer as DateContainer,
    MainStyleDateWrapper as DateWrapper,
    MainStyleDropIcon as DropIcon,
    MainStyleFormColumn as FormColumn,
    MainStyleFormWrapper as FormWrapper,
    MainStyleFullContent as FullContent,
    MainStyleHomeContainer as HomeContainer,
    MainStyleInfoWrapper as InfoWrapper,
    MainStyleLimited as Limited,
    MainStyleLinks as Links,
    MainStyleMiddleContent as MiddleContent,
    MainStyleModalFooter as ModalFooter,
    MainStyleScrollWrapper as ScrollWrapper,
    MainStyleSimpleButton as SimpleButton,
    MainStyleTabContent as TabContent,
    MainStyleTitle as Title,
    MainStyleTopHeader as TopHeader
} from 'erxes-ui';

export {
  BoxRoot,
  FullContent,
  ModalFooter,
  InfoWrapper,
  Links,
  FormWrapper,
  FormColumn,
  CenterContent,
  ActivityContent,
  DropIcon,
  MiddleContent,
  HomeContainer,
  DateWrapper,
  CloseModal,
  ScrollWrapper,
  DateContainer,
  TabContent,
  ButtonRelated,
  SimpleButton,
  TopHeader,
  Title,
  Count,
  Limited
};
