pipeline:
  test:
    image: node:10.16.0-slim
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn install
      - yarn lint

  build:
    image: node:10.16.0-slim
    commands:
      - apt-get update && apt-get install -y git
      - git checkout $DRONE_COMMIT_BRANCH
      - yarn build
    when:
      branch:
        - master
        - develop
      event:
        - push

  build_tag:
    image: node:10.16.0-slim
    commands:
      - yarn build
      - tar -zcf ${DRONE_REPO_NAME}_${DRONE_TAG}.tar.gz dist static .env.sample package.json yarn.lock
    when:
      event:
        - tag

  github_prerelease:
    image: plugins/github-release
    secrets: [ github_token ]
    prerelease: true
    files:
      - ${DRONE_REPO_NAME}_${DRONE_TAG}.tar.gz
    checksum:
      - sha256
    when:
      event:
        - tag
      ref:
        include:
          - "refs/tags/*rc*"
          - "refs/tags/*alpha*"
          - "refs/tags/*beta*"

  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - ${DRONE_REPO_NAME}_${DRONE_TAG}.tar.gz
    checksum:
      - sha256
    when:
      event:
        - tag
      ref:
        include:
          - "refs/tags/*"
        exclude:
          - "refs/tags/*rc*"
          - "refs/tags/*alpha*"
          - "refs/tags/*beta*"

  docker_publish:
    image: plugins/docker
    repo: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
    dockerfile: Dockerfile
    secrets:
      - source: docker_hub_username
        target: docker_username
      - source: docker_hub_password
        target: docker_password
    tags:
      - ${DRONE_BRANCH}
    when:
      branch:
        - master
        - develop
      event:
        - push

  docker_publish_tag:
    image: plugins/docker
    repo: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
    dockerfile: Dockerfile
    secrets:
      - source: docker_hub_username
        target: docker_username
      - source: docker_hub_password
        target: docker_password
    tags:
      - ${DRONE_TAG}
    when:
      event:
        - tag
