export const ACTIVITY_MODULES = {
  NAME: 'NAME',
  STATUS: 'STATUS',
  PRIORITY: 'PRIORITY',
  START_DATE: 'START_DATE',
  END_DATE: 'END_DATE',
  ASSIGNEE: 'ASSIGNEE',
  NOTE: 'NOTE',
};

export const ACTIVITY_ACTIONS = {
  CREATED: 'CREATED',
  CHANGED: 'CHANGED',
  REMOVED: 'REMOVED',
} as const;
