import { TAutomationRuntimeOutputDefinition } from 'erxes-api-shared/core-modules';

const SALES_DEAL_TRIGGER_OUTPUT: TAutomationRuntimeOutputDefinition = {
  variables: [
    { key: '_id', label: 'Deal ID', field: '_id' },
    { key: 'name', label: 'Deal name' },
    { key: 'number', label: 'Deal number' },
    { key: 'description', label: 'Description' },
    { key: 'status', label: 'Status' },
    { key: 'priority', label: 'Priority' },
    { key: 'score', label: 'Score' },
    {
      key: 'stageId',
      label: 'Stage ID',
      exposure: 'reference',
      field: 'stageId',
      referenceType: 'sales:sales.stage',
    },
    {
      key: 'initialStageId',
      label: 'Initial stage ID',
      exposure: 'reference',
      field: 'initialStageId',
      referenceType: 'sales:sales.stage',
    },
    { key: 'stageChangedDate', label: 'Stage changed date' },
    { key: 'startDate', label: 'Start date' },
    { key: 'closeDate', label: 'Close date' },
    { key: 'totalAmount', label: 'Total amount' },
    { key: 'unUsedTotalAmount', label: 'Unused total amount' },
    { key: 'bothTotalAmount', label: 'Both total amount' },
    {
      key: 'userId',
      label: 'Created by',
      exposure: 'reference',
      field: 'userId',
      referenceType: 'core:user',
    },
    {
      key: 'assignedUserIds',
      label: 'Assigned users',
      exposure: 'reference',
      field: 'assignedUserIds',
      referenceType: 'core:user',
    },
    {
      key: 'watchedUserIds',
      label: 'Watched users',
      exposure: 'reference',
      field: 'watchedUserIds',
      referenceType: 'core:user',
    },
    {
      key: 'labelIds',
      label: 'Labels',
      exposure: 'reference',
      field: 'labelIds',
    },
    { key: 'tagIds', label: 'Tags', exposure: 'reference', field: 'tagIds' },
    {
      key: 'branchIds',
      label: 'Branches',
      exposure: 'reference',
      field: 'branchIds',
    },
    {
      key: 'departmentIds',
      label: 'Departments',
      exposure: 'reference',
      field: 'departmentIds',
    },
    {
      key: 'customers',
      label: 'Customers',
      exposure: 'reference',
      field: 'customers',
      referenceType: 'core:customer',
    },
    {
      key: 'companies',
      label: 'Companies',
      exposure: 'reference',
      field: 'companies',
      referenceType: 'core:company',
    },
    { key: 'productsData.amount', label: 'Products amount' },
    { key: 'link', label: 'Deal link' },
    { key: 'pipelineLabels', label: 'Pipeline labels' },
    { key: 'createdAt', label: 'Created at' },
    { key: 'updatedAt', label: 'Updated at' },
  ],
  propertySource: {
    key: 'properties',
    label: 'Deal properties',
    propertyType: 'sales:deal',
  },
};

export const salesAutomationContants = {
  triggers: [
    {
      moduleName: 'sales',
      collectionName: 'deals',
      icon: 'IconPigMoney',
      label: 'Sales pipeline',
      description:
        'Start with a blank workflow that enrolls and is triggered off sales pipeline item',
      output: SALES_DEAL_TRIGGER_OUTPUT,
    },
    {
      moduleName: 'sales',
      collectionName: 'deals',
      relationType: 'probability',
      icon: 'IconPigMoney',
      label: 'Deal reaches stage probability',
      description:
        'Start this workflow when a deal moves to a stage with the selected probability.',
      isCustom: true,
      output: SALES_DEAL_TRIGGER_OUTPUT,
    },
  ],
  actions: [
    {
      moduleName: 'sales',
      collectionName: 'deals',
      method: 'create',
      icon: 'IconPigMoney',
      label: 'Create deal',
      description: 'Create deal',
      isTargetSource: true,
      targetSourceType: 'sales:sales.deal',
      allowTargetFromActions: true,
    },
    {
      moduleName: 'sales',
      collectionName: 'checklist',
      method: 'create',
      icon: 'IconPigMoney',
      label: 'Create sales checklist',
      description: 'Create sales checklist',
      isAvailable: true,
    },
  ],
};
