export const INTL_LANGUAGES = {
  English: 'en-US',
  'English (UK)': 'en-GB',
  Spanish: 'es-ES',
  'Spanish (Mexico)': 'es-MX',
  French: 'fr-FR',
  'French (Canada)': 'fr-CA',
  German: 'de-DE',
  Italian: 'it-IT',
  Portuguese: 'pt-PT',
  'Portuguese (Brazil)': 'pt-BR',
  Russian: 'ru-RU',
  'Chinese (Simplified)': 'zh-CN',
  'Chinese (Traditional)': 'zh-TW',
  Japanese: 'ja-JP',
  Korean: 'ko-KR',
  Arabic: 'ar-SA',
  Hindi: 'hi-IN',
  Dutch: 'nl-NL',
  Swedish: 'sv-SE',
  Norwegian: 'no-NO',
  Danish: 'da-DK',
  Finnish: 'fi-FI',
  Polish: 'pl-PL',
  Czech: 'cs-CZ',
  Hungarian: 'hu-HU',
  Romanian: 'ro-RO',
  Bulgarian: 'bg-BG',
  Croatian: 'hr-HR',
  Serbian: 'sr-RS',
  Slovak: 'sk-SK',
  Slovenian: 'sl-SI',
  Estonian: 'et-EE',
  Latvian: 'lv-LV',
  Lithuanian: 'lt-LT',
  Greek: 'el-GR',
  Turkish: 'tr-TR',
  Hebrew: 'he-IL',
  Thai: 'th-TH',
  Vietnamese: 'vi-VN',
  Indonesian: 'id-ID',
  Malay: 'ms-MY',
  Filipino: 'fil-PH',
  Ukrainian: 'uk-UA',
  Belarusian: 'be-BY',
  Kazakh: 'kk-KZ',
  Uzbek: 'uz-UZ',
  Georgian: 'ka-GE',
  Armenian: 'hy-AM',
  Azerbaijani: 'az-AZ',
  Persian: 'fa-IR',
  Urdu: 'ur-PK',
  Bengali: 'bn-BD',
  Tamil: 'ta-IN',
  Telugu: 'te-IN',
  Marathi: 'mr-IN',
  Gujarati: 'gu-IN',
  Kannada: 'kn-IN',
  Malayalam: 'ml-IN',
  Punjabi: 'pa-IN',
  Nepali: 'ne-NP',
  Sinhala: 'si-LK',
  Burmese: 'my-MM',
  Khmer: 'km-KH',
  Lao: 'lo-LA',
  Mongolian: 'mn-MN',
  Tibetan: 'bo-CN',
  Swahili: 'sw-KE',
  Afrikaans: 'af-ZA',
  Amharic: 'am-ET',
  Yoruba: 'yo-NG',
  Igbo: 'ig-NG',
  Hausa: 'ha-NG',
};
