export const importTemplates: Record<
  string,
  { filename: string; headers: string[] }
> = {
  'core:product.product': {
    filename: 'products-template.csv',
    headers: [
      'Name',
      'Code',
      'Unit Price',
      'UOM',
      'Category',
      'Vendor',
      'Brands',
      'Tags',
      'Short Name',
      'Type',
      'Status',
      'Description',
      'Barcodes',
      'Barcode Description',
    ],
  },

  'core:contact.customer': {
    filename: 'customers-template.csv',
    headers: [
      'First Name',
      'Last Name',
      'Middle Name',
      'Email',
      'Phone',
      'Position',
      'Department',
      'Description',
      'Code',
      'Sex',
      'Birth Date',
      'Status',
      'Email Validation Status',
      'Phone Validation Status',
      'Tags',
    ],
  },

  'core:contact.company': {
    filename: 'companies-template.csv',
    headers: [
      'Name',
      'Emails',
      'Phones',
      'Website',
      'Industry',
      'Size',
      'Status',
      'Business Type',
      'Description',
      'Employees',
      'Links',
      'Tags',
      'Code',
      'Location',
    ],
  },

  'core:user.user': {
    filename: 'team-members-template.csv',
    headers: [
      'Username',
      'Email',
      'Employee ID',
      'Is Active',
      'First Name',
      'Middle Name',
      'Last Name',
      'Short Name',
      'Full Name',
      'Birth Date',
      'Work Started Date',
      'Location',
      'Description',
      'Operator Phone',
      'Brands',
      'Departments',
      'Branches',
    ],
  },
};
