import {
  ImportHeaderDefinition,
  TExportHandlers,
} from 'erxes-api-shared/core-modules';

export const getPosItemsExportHeaders: TExportHandlers['getExportHeaders'] =
  async (): Promise<ImportHeaderDefinition[]> => {
    return [
      { key: 'orderId', label: 'Order ID', isDefault: false },
      { key: 'itemId', label: 'Item ID', isDefault: false },
      { key: 'number', label: 'Number', isDefault: true },
      { key: 'createdAt', label: 'Created Date', isDefault: true },
      { key: 'paidDate', label: 'Paid Date', isDefault: false },
      { key: 'dueDate', label: 'Due Date', isDefault: false },
      { key: 'status', label: 'Status', isDefault: false },
      { key: 'posId', label: 'POS ID', isDefault: false },
      { key: 'posToken', label: 'POS Token', isDefault: false },
      { key: 'posName', label: 'POS Name', isDefault: true },
      { key: 'branchId', label: 'Branch ID', isDefault: false },
      { key: 'branch', label: 'Branch', isDefault: false },
      { key: 'departmentId', label: 'Department ID', isDefault: false },
      { key: 'department', label: 'Department', isDefault: false },
      { key: 'subBranchId', label: 'Sub Branch ID', isDefault: false },
      { key: 'userId', label: 'Cashier User ID', isDefault: false },
      { key: 'cashier', label: 'Cashier', isDefault: false },
      { key: 'type', label: 'Type', isDefault: false },
      { key: 'billType', label: 'Bill Type', isDefault: false },
      { key: 'registerNumber', label: 'Company RD', isDefault: false },
      { key: 'customerId', label: 'Customer ID', isDefault: false },
      { key: 'customerType', label: 'Customer Type', isDefault: false },
      { key: 'customer', label: 'Customer', isDefault: false },
      { key: 'productId', label: 'Product ID', isDefault: false },
      { key: 'productCode', label: 'Code', isDefault: true },
      { key: 'productName', label: 'Product Name', isDefault: true },
      { key: 'categoryCode', label: 'Category Code', isDefault: false },
      { key: 'categoryName', label: 'Category Name', isDefault: false },
      { key: 'barcode', label: 'Barcode', isDefault: false },
      { key: 'count', label: 'Count', isDefault: true },
      { key: 'unitPrice', label: 'Unit Price', isDefault: true },
      { key: 'discountAmount', label: 'Discount', isDefault: false },
      { key: 'discountPercent', label: 'Discount Percent', isDefault: false },
      { key: 'totalAmount', label: 'Total Amount', isDefault: true },
      { key: 'finalAmount', label: 'Final Amount', isDefault: false },
      { key: 'cashAmount', label: 'Cash Amount', isDefault: false },
      { key: 'mobileAmount', label: 'Mobile Amount', isDefault: false },
      { key: 'paymentType', label: 'Payment Type', isDefault: false },
      { key: 'paidAmounts', label: 'Paid Amounts JSON', isDefault: false },
      { key: 'description', label: 'Description', isDefault: false },
      { key: 'origin', label: 'Origin', isDefault: false },
      { key: 'itemDescription', label: 'Item Description', isDefault: false },
    ];
  };
