const reportTemplates = [
    {
        serviceType: 'deal',
        title: 'Deals chart',
        serviceName: 'cards',
        description: 'Deals charts',
        charts: [
            'DealsTotalCount',
            'DealCountByTag',
            'DealCountByLabel',
            'DealCountByCustomProperties',
            'DealAverageAmountByRep',
            'DealLeaderBoardAmountClosedByRep',
            'DealsClosedLostByRep',
            'DealsClosedWonByRep',
            'DealRevenueByStage',
            'DealsTotalCountByDueDate',
            'DealAverageTimeSpentInEachStage',
            'ClosedRevenueByMonthWithDealTotalAndClosedRevenueBreakdown',
        ],
        img: 'https://sciter.com/wp-content/uploads/2022/08/chart-js.png',
    },
    {
        serviceType: 'task',
        title: 'Tasks chart',
        serviceName: 'cards',
        description: 'Cards conversation charts',
        charts: [
            'TaskAverageTimeToCloseByReps',
            'TaskAverageTimeToCloseByLabel',
            'TaskAverageTimeToCloseByTags',
            'TaskCustomProperties',
            'TaskClosedTotalsByReps',
            'TaskClosedTotalsByLabel',
            'TaskClosedTotalsByTags',
            'TasksIncompleteTotalsByReps',
            'TasksIncompleteTotalsByLabel',
            'TasksIncompleteTotalsByTags',
            'AllTasksIncompleteByDueDate',
            'TasksIncompleteAssignedToTheTeamByDueDate',
            'TasksIncompleteAssignedToMeByDueDate',
            'TaskCountInEachPipeline',
            'TaskCountInEachStage',
            'TaskCountByCompanies',
        ],
        img: 'https://cdn.mos.cms.futurecdn.net/S5bicwPe8vbP9nt3iwAwwi.jpg',
    },
    {
        serviceType: 'ticket',
        title: 'Tickets chart',
        serviceName: 'cards',
        description: 'Tickets conversation charts',
        charts: [
            'TicketCustomProperties',
            'TicketAverageTimeToCloseOverTime',
            'TicketClosedTotalsByRep',
            'TicketTotalsByStatus',
            'TicketTotalsByLabelPriorityTag',
            'TicketTotalsOverTime',
            'TicketAverageTimeToCloseByRep',
            'TicketAverageTimeToClose',
            'TicketTotalsBySource',
            'TicketsCardCountAssignedUser',
            'TicketsStageDateRange',
            'TicketCountInEachPipeline',
            'TicketCountInEachStage',
            'TicketCountByCompanies',
        ],
        img: 'https://sciter.com/wp-content/uploads/2022/08/chart-js.png',
    },
];

export default reportTemplates;