import {
  IconAlarm,
  IconAlertTriangle,
  IconArrowsShuffle,
  IconArticle,
  IconBell,
  IconBinoculars,
  IconBook,
  IconBrain,
  IconBriefcase,
  IconBulb,
  IconCamera,
  IconChartBar,
  IconChartPie,
  IconClipboard,
  IconClipboardCopy,
  IconClock,
  IconCompass,
  IconCreditCard,
  IconDatabase,
  IconDeviceDesktop,
  IconDiamond,
  IconEye,
  IconFlag,
  IconFolder,
  IconGift,
  IconGraph,
  IconHeart,
  IconHome,
  IconHourglass,
  IconInbox,
  IconLanguage,
  IconLock,
  IconMail,
  IconMedal,
  IconMessage,
  IconMessageDots,
  IconMoodSmile,
  IconMoon,
  IconMusic,
  IconNote,
  IconPalette,
  IconPaperclip,
  IconPencil,
  IconPhoneCall,
  IconPigMoney,
  IconPuzzle,
  IconRocket,
  IconScale,
  IconSearch,
  IconSend,
  IconSettings,
  IconShieldLock,
  IconSpeakerphone,
  IconStar,
  IconSunset,
  IconThumbUp,
  IconTicket,
  IconTool,
  IconTools,
  IconTrees,
  IconUmbrella,
  IconUser,
  IconUsers,
  IconVideo,
  IconWorld,
  type Icon,
} from '@tabler/icons-react';

const CATEGORY_ICONS: Record<string, Icon> = {
  alarm: IconAlarm,
  briefcase: IconBriefcase,
  earthgrid: IconWorld,
  compass: IconCompass,
  idea: IconBulb,
  diamond: IconDiamond,
  piggybank: IconPigMoney,
  piechart: IconChartPie,
  scale: IconScale,
  megaphone: IconSpeakerphone,
  tools: IconTools,
  umbrella: IconUmbrella,
  'bar-chart': IconChartBar,
  chart: IconChartBar,
  star: IconStar,
  'head-1': IconBrain,
  settings: IconSettings,
  users: IconUsers,
  paintpalette: IconPalette,
  flag: IconFlag,
  'phone-call': IconPhoneCall,
  home: IconHome,
  puzzle: IconPuzzle,
  medal: IconMedal,
  like: IconThumbUp,
  book: IconBook,
  clipboard: IconClipboard,
  computer: IconDeviceDesktop,
  paste: IconClipboardCopy,
  'folder-1': IconFolder,
  sunset: IconSunset,
  'heart-alt': IconHeart,
  'music-1': IconMusic,
  pencil: IconPencil,
  database: IconDatabase,
  videocamera: IconVideo,
  'clipboard-1': IconNote,
  camera: IconCamera,
  'shuffle-1': IconArrowsShuffle,
  hourglass: IconHourglass,
  'envelope-alt': IconMail,
  postcard: IconMail,
  'graph-bar': IconGraph,
  'comment-alt-message': IconMessageDots,
  chat: IconMessage,
  smile: IconMoodSmile,
  wallclock: IconClock,
  trees: IconTrees,
  gift: IconGift,
  'moon-1': IconMoon,
  rocket: IconRocket,
  'credit-card': IconCreditCard,
  lock: IconLock,
  shield: IconShieldLock,
  ticket: IconTicket,
  article: IconArticle,
  inbox: IconInbox,
  search: IconSearch,
  bell: IconBell,
  eye: IconEye,
  alert: IconAlertTriangle,
  wrench: IconTool,
  binoculars: IconBinoculars,
  send: IconSend,
  paperclip: IconPaperclip,
  user: IconUser,
  language: IconLanguage,
};

export const categoryIcon = (name?: string | null): Icon =>
  (name && CATEGORY_ICONS[name]) || IconBook;
