module.exports = {
  srcDir: __dirname,
  name: 'tickets',
  port: 3050,
  scope: 'tickets',
  url: 'http://localhost:3050/remoteEntry.js',
  exposes: {
    './routes': './src/routes.tsx',
    './settings': './src/Settings.tsx',
    './propertyGroupForm': './src/propertyGroupForm.tsx',
    './segmentForm': './src/segmentForm.tsx',
    './contactDetailRightSidebar': './src/RightSidebar.tsx',
    './selectRelation': './src/common/SelectRelation.tsx',
    './invoiceDetailRightSection': './src/common/Item.tsx',
  },
  routes: {
    url: 'http://localhost:3050/remoteEntry.js',
    scope: 'tickets',
    module: './routes',
  },
  propertyGroupForm: './propertyGroupForm',
  segmentForm: './segmentForm',
  activityLog: './activityLog',
  automation: './automation',
  contactDetailRightSidebar: './contactDetailRightSidebar',
  invoiceDetailRightSection: './invoiceDetailRightSection',
  selectRelation: './selectRelation',
  menus: [
    {
      text: 'Ticket',
      url: '/ticket',
      icon: 'icon-ticket',
      location: 'mainNavigation',
      permission: 'showTickets',
    },
    {
      text: 'Ticket Pipelines',
      to: '/settings/boards/ticket',
      image: '/images/icons/erxes-19.svg',
      location: 'settings',
      scope: 'tickets',
      action: 'ticketsAll',
      permissions: [
        'ticketBoardsAdd',
        'ticketBoardsEdit',
        'ticketBoardsRemove',
        'ticketPipelinesAdd',
        'ticketPipelinesEdit',
        'ticketPipelinesUpdateOrder',
        'ticketPipelinesRemove',
        'ticketPipelinesArchive',
        'ticketPipelinesCopied',
        'ticketStagesAdd',
        'ticketStagesEdit',
        'ticketStagesUpdateOrder',
        'ticketStagesRemove',
      ],
    },
  ],
};
