import {
  IconAt,
  IconCalendarEvent,
  IconCheck,
  IconChevronDown,
  IconCircleCheck,
  IconGenderBigender,
  IconListDetails,
  IconNumbers,
  IconPaperclip,
  IconPhoneSpark,
  IconTextScan2,
  IconTextSize,
  IconUserCircle,
  IconWorld,
} from '@tabler/icons-react';

export const COUNTRIES = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

export const FORM_FIELD_TYPES = [
  { value: 'text', label: 'Text', icon: <IconTextSize /> },
  { value: 'number', label: 'Number', icon: <IconNumbers /> },
  { value: 'boolean', label: 'Checkbox', icon: <IconCheck /> },
  { value: 'date', label: 'Date', icon: <IconCalendarEvent /> },
  { value: 'select', label: 'Select', icon: <IconChevronDown /> },
  {
    value: 'select:countries',
    label: 'Countries',
    icon: <IconWorld />,
    defaultOptions: COUNTRIES,
    defaultAllowSearch: true,
  },
  { value: 'textarea', label: 'Textarea', icon: <IconTextScan2 /> },
  { value: 'radio', label: 'Radio Group', icon: <IconCircleCheck /> },
  { value: 'check', label: 'Checkbox Group', icon: <IconListDetails /> },
  { value: 'file', label: 'Attachment', icon: <IconPaperclip /> },

  // Customer core fields
  { value: 'core:customer:avatar', label: 'Avatar', icon: <IconUserCircle /> },
  {
    value: 'core:customer:firstName',
    label: 'First Name',
    icon: <IconTextSize />,
  },
  {
    value: 'core:customer:middleName',
    label: 'Middle Name',
    icon: <IconTextSize />,
  },
  {
    value: 'core:customer:lastName',
    label: 'Last Name',
    icon: <IconTextSize />,
  },
  { value: 'core:customer:email', label: 'Email', icon: <IconAt /> },
  {
    value: 'core:customer:phone',
    label: 'Phone',
    icon: <IconPhoneSpark />,
  },
  {
    value: 'core:customer:description',
    label: 'Description',
    icon: <IconTextSize />,
  },
  { value: 'core:customer:sex', label: 'Gender', icon: <IconGenderBigender /> },
  {
    value: 'core:customer:birthDate',
    label: 'Birth date',
    icon: <IconCalendarEvent />,
  },
];

export type FormFieldType = (typeof FORM_FIELD_TYPES)[number];

export type FormGroupKey = 'basic' | 'core:customer';
export type GroupedFields = Record<FormGroupKey, FormFieldType[]>;

export interface FormGroupMetadata {
  label: string;
  description?: string;
}
