export const COMPANY_BUSINESS_TYPES = [
    'Analyst',
    'Competitor',
    'Customer',
    'Integrator',
    'Investor',
    'Partner',
    'Press',
    'Prospect',
    'Reseller',
    'Other'
  ];
  
  export const DEFAULT_COMPANY_INDUSTRY_TYPES = [
    'Aerospace & Defense',
    'Air Freight & Logistics',
    'Airlines',
    'Auto Components',
    'Automobiles',
    'Banks',
    'Beverages',
    'Biotechnology',
    'Building Products',
    'Capital Markets',
    'Chemicals',
    'Commercial Services & Supplies',
    'Communications Equipment',
    'Construction & Engineering',
    'Construction Materials',
    'Consumer Finance',
    'Containers & Packaging',
    'Distributors',
    'Diversified Consumer Services',
    'Diversified Financial Services',
    'Diversified Telecommunication Services',
    'Electric Utilities',
    'Electrical Equipment',
    'Electronic Equipment, Instruments & Components',
    'Energy Equipment & Services',
    'Entertainment',
    'Equity Real Estate Investment Trusts (REITs)',
    'Food & Staples Retailing',
    'Food Products',
    'Gas Utilities',
    'Health Care Equipment & Supplies',
    'Health Care Providers & Services',
    'Health Care Technology',
    'Hotels, Restaurants & Leisure',
    'Household Durables',
    'Household Products',
    'Independent Power and Renewable Electricity Producers',
    'Industrial Conglomerates',
    'Insurance',
    'Interactive Media & Services',
    'Internet & Direct Marketing Retail',
    'IT Services',
    'Leisure Products',
    'Life Sciences Tools & Services',
    'Machinery',
    'Marine',
    'Media',
    'Metals & Mining',
    'Mortgage Real Estate Investment Trusts (REITs)',
    'Multi-Utilities',
    'Multiline Retail',
    'Oil, Gas & Consumable Fuels',
    'Paper & Forest Products',
    'Personal Products',
    'Pharmaceuticals',
    'Professional Services',
    'Real Estate Management & Development',
    'Road & Rail',
    'Semiconductors & Semiconductor Equipment',
    'Software',
    'Specialty Retail',
    'Technology Hardware, Storage & Peripherals',
    'Textiles, Apparel & luxury goods',
    'Thrifts & Mortgage Finance',
    'Tobacco',
    'Trading Companies & Distributors',
    'Transportation Infrastructure',
    'Water Utilities',
    'Wireless Telecommunication Services',
    'Transportation',
    'Mining',
    'Finance',
    'Group company',
    'Government',
    'Utility',
    'Education',
    'Manufacturing',
    'Communication',
    'Retail',
    'Health',
    'Construction',
    'Management'
  ];