export const ACTIONS = {
  WAIT: "WAIT",
  IF: "IF",
  SIMPLE_IF: "SIMPLE_IF",
  GO_TO: "GO_TO",
  ADD_TAGS: "ADD_TAGS",
  REMOVE_TAGS: "REMOVE_TAGS",
  ADD_TASK: "ADD_TASK",
  ADD_DEAL: "ADD_DEAL",
  REMOVE_DEAL: "REMOVE_DEAL",
};
