export const TICKET_STATUS_TYPES = {
  NEW: 1,
  OPEN: 2,
  IN_PROGRESS: 3,
  RESOLVED: 4,
  CLOSED: 5,
  CANCELLED: 6,
};

export const TICKET_STATUS_TYPE_NAMES = {
  [TICKET_STATUS_TYPES.NEW]: 'New',
  [TICKET_STATUS_TYPES.OPEN]: 'Open',
  [TICKET_STATUS_TYPES.IN_PROGRESS]: 'In progress',
  [TICKET_STATUS_TYPES.RESOLVED]: 'Resolved',
  [TICKET_STATUS_TYPES.CLOSED]: 'Closed',
  [TICKET_STATUS_TYPES.CANCELLED]: 'Cancelled',
};
