export const currency = [
  { value: 'Albanian lekë Lek', label: 'Albanian lekë Lek' },
  { value: 'Algerian dinars د.ج.‏', label: 'Algerian dinars د.ج.‏' },
  { value: 'Angolan kwanzas Kz', label: 'Angolan kwanzas Kz' },
  { value: 'Armenian drams դր.', label: 'Armenian drams դր.' },
  { value: 'Australian dollars $', label: 'Australian dollars $' },
  { value: 'Azerbaijani manats ман.', label: 'Azerbaijani manats ман.' },
  { value: 'Belarusian rubles BYR', label: 'Belarusian rubles BYR' },
  { value: 'Bolivian bolivianos Bs', label: 'Bolivian bolivianos Bs' },
  {
    value: 'Bosnia-Herzegovina convertible marks KM"',
    label: 'Bosnia-Herzegovina convertible marks KM"'
  },
  { value: 'Brazilian reals R$', label: 'Brazilian reals R$' },
  { value: 'British pounds sterling £', label: 'British pounds sterling £' },
  { value: 'Bulgarian leva лв.', label: 'Bulgarian leva лв.' },
  { value: 'Burundian francs FBu', label: 'Burundian francs FBu' },
  { value: 'Canadian dollars $', label: 'Canadian dollars $' },
  { value: 'Cape Verdean escudos CV$', label: 'Cape Verdean escudos CV$' },
  { value: 'CFA francs BEAC FCFA', label: 'CFA francs BEAC FCFA' },
  { value: 'Chinese yuan CN¥', label: 'Chinese yuan CN¥' },
  { value: 'Colombian pesos $', label: 'Colombian pesos $' },
  { value: 'Comorian francs FC', label: 'Comorian francs FC' },
  { value: 'Congolese francs FrCD', label: 'Congolese francs FrCD' },
  { value: 'Czech Republic korunas Kč', label: 'Czech Republic korunas Kč' },
  { value: 'Djiboutian francs Fdj', label: 'Djiboutian francs Fdj' },
  { value: 'Egyptian pounds ج.م.‏', label: 'Egyptian pounds ج.م.‏' },
  { value: 'Ethiopian birrs Br', label: 'Ethiopian birrs Br' },
  { value: 'Georgian laris GEL', label: 'Georgian laris GEL' },
  { value: 'Ghanaian cedis GH₵', label: 'Ghanaian cedis GH₵' },
  { value: 'Guatemalan quetzals Q', label: 'Guatemalan quetzals Q' },
  { value: 'Honduran lempiras L', label: 'Honduran lempiras L' },
  { value: 'Hong Kong dollars $', label: 'Hong Kong dollars $' },
  { value: 'Hungarian forints Ft', label: 'Hungarian forints Ft' },
  { value: 'Indonesian rupiahs Rp', label: 'Indonesian rupiahs Rp' },
  { value: 'Iraqi dinars د.ع.‏', label: 'Iraqi dinars د.ع.‏' },
  { value: 'Israeli new shekels ₪', label: 'Israeli new shekels ₪' },
  { value: 'Jordanian dinars د.أ.‏', label: 'Jordanian dinars د.أ.‏' },
  { value: 'Kazakhstani tenges тңг.', label: 'Kazakhstani tenges тңг.' },
  { value: 'Kuwaiti dinars د.ك.‏', label: 'Kuwaiti dinars د.ك.‏' },
  { value: 'Lebanese pounds ل.ل.‏', label: 'Lebanese pounds ل.ل.‏' },
  { value: 'Lithuanian litai Lt', label: 'Lithuanian litai Lt' },
  { value: 'Macanese patacas MOP$', label: 'Macanese patacas MOP$' },
  { value: 'Macedonian denari MKD', label: 'Macedonian denari MKD' },
  { value: 'Malagasy Ariaries MGA', label: 'Malagasy Ariaries MGA' },
  { value: 'Malaysian ringgits RM', label: 'Malaysian ringgits RM' },
  { value: 'Mauritanian ouguiya UM', label: 'Mauritanian ouguiya UM' },
  { value: 'Moldovan lei MDL', label: 'Moldovan lei MDL' },
  { value: 'Mongolian tögrög ₮', label: 'Mongolian tögrög ₮' },
  { value: 'Moroccan dirhams د.م.‏', label: 'Moroccan dirhams د.م.‏' },
  { value: 'Mozambican meticals MTn', label: 'Mozambican meticals MTn' },
  { value: 'Namibian dollars N$', label: 'Namibian dollars N$' },
  { value: 'Nepalese rupees नेरू', label: 'Nepalese rupees नेरू' },
  { value: 'New Taiwan dollars NT$', label: 'New Taiwan dollars NT$' },
  { value: 'Nicaraguan córdobas C$', label: 'Nicaraguan córdobas C$' },
  { value: 'Norwegian kroner kr', label: 'Norwegian kroner kr' },
  { value: 'Pakistani rupees ₨', label: 'Pakistani rupees ₨' },
  { value: 'Panamanian balboas B/.', label: 'Panamanian balboas B/.' },
  { value: 'Papua New Guinean kina K', label: 'Papua New Guinean kina K' },
  { value: 'Peruvian nuevos soles S/.', label: 'Peruvian nuevos soles S/.' },
  { value: 'Qatari rials ر.ق.‏', label: 'Qatari rials ر.ق.‏' },
  { value: 'Russian rubles руб.', label: 'Russian rubles руб.' },
  { value: 'Saudi riyals ر.س.‏', label: 'Saudi riyals ر.س.‏' },
  { value: 'Serbian dinars дин.', label: 'Serbian dinars дин.' },
  { value: 'Singapore dollars $', label: 'Singapore dollars $' },
  { value: 'Somali shillings Ssh', label: 'Somali shillings Ssh' },
  { value: 'South African rand R', label: 'South African rand R' },
  { value: 'Sri Lankan rupees SL Re', label: 'Sri Lankan rupees SL Re' },
  { value: 'Surinamese dollars $', label: 'Surinamese dollars $' },
  { value: 'Syrian pounds ل.س.‏', label: 'Syrian pounds ل.س.‏' },
  { value: 'Tanzanian shillings TSh', label: 'Tanzanian shillings TSh' },
  { value: 'Tongan paʻanga T$', label: 'Tongan paʻanga T$' },
  {
    value: 'Trinidad and Tobago dollars $',
    label: 'Trinidad and Tobago dollars $'
  },
  { value: 'UAE dirhams د.إ.‏', label: 'UAE dirhams د.إ.‏' },
  { value: 'Ugandan shillings USh', label: 'Ugandan shillings USh' },
  { value: 'Uzbekistan som UZS', label: 'Uzbekistan som UZS' },
  { value: 'Venezuelan bolívars Bs.F.', label: 'Venezuelan bolívars Bs.F.' },
  { value: 'Yemeni rials ر.ي.‏', label: 'Yemeni rials ر.ي.‏' },
  { value: 'Zambian kwachas ZK', label: 'Zambian kwachas ZK' }
];

export const measurements = [
  { value: 'Microliter	μL', label: 'Microliter	μL' },
  { value: 'Micrometer	μM', label: 'Micrometer	μM' },
  { value: 'Acre	ACR', label: 'Acre	ACR' },
  { value: 'Ampere	A', label: 'Ampere	A' },
  { value: 'Years	YR', label: 'Years	YR' },
  { value: 'Arpent	ARP', label: 'Arpent	ARP' },
  { value: 'Bundle	BE', label: 'Bundle	BE' },
  { value: 'Board Foot	BFT', label: 'Board Foot	BFT' },
  { value: 'Bag	BAG', label: 'Bag	BAG' },
  { value: 'Bucket	BCK', label: 'Bucket	BCK' },
  { value: 'Book	BK', label: 'Book	BK' },
  { value: 'Bale	BL', label: 'Bale	BL' },
  { value: 'Barrel	BBL', label: 'Barrel	BBL' },
  { value: 'Bottle	BOT', label: 'Bottle	BOT' },
  { value: 'Bushel	BU', label: 'Bushel	BU' },
  { value: 'Box	BOX', label: 'Box	BOX' },
  { value: 'Nanometer	NAM', label: 'Nanometer	NAM' },
  { value: 'Can	CAN', label: 'Can	CAN' },
  { value: 'Hundred	CEN', label: 'Hundred	CEN' },
  { value: 'Card	CG', label: 'Card	CG' },
  { value: 'Square centimeter	CM2', label: 'Square centimeter	CM2' },
  { value: 'Cubic centimeter	CM3', label: 'Cubic centimeter	CM3' },
  { value: 'Centimeter	CM', label: 'Centimeter	CM' },
  { value: 'Crate	CRT', label: 'Crate	CRT' },
  { value: 'Case	CE', label: 'Case	CE' },
  { value: 'Carton	CAR', label: 'Carton	CAR' },
  { value: 'Day	DAY', label: 'Day	DAY' },
  { value: 'Deal	DE', label: 'Deal	DE' },
  { value: 'Cubic decimeter	DM3', label: 'Cubic decimeter	DM3' },
  { value: 'Decimeter	DM', label: 'Decimeter	DM' },
  { value: 'Drum	DRM', label: 'Drum	DRM' },
  { value: 'Display	DS', label: 'Display	DS' },
  { value: 'Dozen	DZN', label: 'Dozen	DZN' },
  { value: 'Job	JOB', label: 'Job	JOB' },
  { value: 'Each	EA', label: 'Each	EA' },
  { value: 'Foot	FT', label: 'Foot	FT' },
  { value: 'Foot Per Minute	FPM', label: 'Foot Per Minute	FPM' },
  { value: 'Square foot	FT2', label: 'Square foot	FT2' },
  { value: 'Cubic foot	FT3', label: 'Cubic foot	FT3' },
  { value: 'US gallon	GAL', label: 'US gallon	GAL' },
  { value: 'Gram	G', label: 'Gram	G' },
  { value: 'Gross	GRO', label: 'Gross	GRO' },
  { value: 'Hectare	HA', label: 'Hectare	HA' },
  { value: 'Hour	H', label: 'Hour	H' },
  { value: 'Inch	IN', label: 'Inch	IN' },
  { value: 'Square inch	IN2', label: 'Square inch	IN2' },
  { value: 'Cubic inch	IN3', label: 'Cubic inch	IN3' },
  { value: 'Kilogram	KG', label: 'Kilogram	KG' },
  { value: 'Square kilometer	KM2', label: 'Square kilometer	KM2' },
  { value: 'Kilometer	KM', label: 'Kilometer	KM' },
  { value: 'Kit	KIT', label: 'Kit	KIT' },
  { value: 'Pound	LB', label: 'Pound	LB' },
  { value: 'Linear Foot	LF', label: 'Linear Foot	LF' },
  { value: 'Lot	LOT', label: 'Lot	LOT' },
  { value: 'Liter	L', label: 'Liter	L' },
  { value: '1000 Board Feet	MBF', label: '1000 Board Feet	MBF' },
  { value: '1000 Cubic Feet	MCF', label: '1000 Cubic Feet	MCF' },
  { value: 'Milligram	MG', label: 'Milligram	MG' },
  { value: 'Square mile	MI2', label: 'Square mile	MI2' },
  { value: 'Thousand	TH', label: 'Thousand	TH' },
  { value: 'Minute	MIN', label: 'Minute	MIN' },
  { value: 'Milliliter	ML', label: 'Milliliter	ML' },
  { value: 'Square millimeter	MM2', label: 'Square millimeter	MM2' },
  { value: 'Millimeter	MM', label: 'Millimeter	MM' },
  { value: 'Month	MON', label: 'Month	MON' },
  { value: 'Square meter	M2', label: 'Square meter	M2' },
  { value: 'Cubic meter	M3', label: 'Cubic meter	M3' },
  { value: 'Meter	M', label: 'Meter	M' },
  { value: 'Ounce	OZ', label: 'Ounce	OZ' },
  { value: 'Fluid Ounce US	FOZ', label: 'Fluid Ounce US	FOZ' },
  { value: 'Group proportion	000', label: 'Group proportion	000' },
  { value: 'Pad	PAD', label: 'Pad	PAD' },
  { value: 'Pallet	PAL', label: 'Pallet	PAL' },
  { value: 'Pack	PAC', label: 'Pack	PAC' },
  { value: 'Pair	PR', label: 'Pair	PR' },
  { value: 'Pint, US liquid	PT', label: 'Pint, US liquid	PT' },
  { value: 'Quart, US liquid	QT', label: 'Quart, US liquid	QT' },
  { value: 'Ream	RM', label: 'Ream	RM' },
  { value: 'Roll	ROL', label: 'Roll	ROL' },
  { value: 'Set	SET', label: 'Set	SET' },
  { value: 'Mile	MI', label: 'Mile	MI' },
  { value: 'Square	SQ', label: 'Square	SQ' },
  { value: 'Sheet	ST', label: 'Sheet	ST' },
  { value: 'Ton, short (2000 lb)	TON', label: 'Ton, short (2000 lb)	TON' },
  {
    value: 'Tonne (metric ton, 1000 kg)	T',
    label: 'Tonne (metric ton, 1000 kg)	T'
  },
  { value: 'Tube	TU', label: 'Tube	TU' },
  { value: 'Vial	VIA', label: 'Vial	VIA' },
  { value: 'Cord	CDS', label: 'Cord	CDS' },
  { value: 'Weeks	WK', label: 'Weeks	WK' },
  { value: 'Watt	W', label: 'Watt	W' },
  { value: 'Square yard	YD2', label: 'Square yard	YD2' },
  { value: 'Cubic yard	YD3', label: 'Cubic yard	YD3' },
  { value: 'Yard	YD', label: 'Yard	YD' },
  { value: 'Lug	LUG', label: 'Lug	LUG' },
  { value: 'Deliverable line item	LE', label: 'Deliverable line item	LE' }
];
