export const CONTENT_TYPE_ARTICLE = 'ARTICLE';

export const CONTENT_TYPE_CATEGORY = 'CATEGORY';

export const CONTENT_TYPE_TOPIC = 'TOPIC';

export const SWITCH_TO_ARTICLE_DISPLAY = 'SWITCH_TO_ARTICLE_DISPLAY';

export const SWITCH_TO_CATEGORY_DISPLAY = 'SWITCH_TO_CATEGORY_DISPLAY';

export const SWITCH_TO_TOPIC_DISPLAY = 'SWITCH_TO_TOPIC_DISPLAY';

export const UPDATE_SEARCH_STRING = 'UPDATE_SEARCH_STRING';

export const CONTENT_TYPE_SEARCH = 'CONTENT_TYPE_SEARCH';
