export const JOURNALS_KEY_LABELS = {
  otherReceivable: "Other Receivable",

  isAmountUseEBarimt: "is Calc EBarimt from Amount",
  isInterestUseEBarimt: "is Calc EBarimt from Interest",
  isLossUseEBarimt: "is Calc EBarimt from Loss",
  transAccount: "Transaction Account",
  normalAccount: "Normal Loan Account",
  expiredAccount: "Expired Loan Account",
  doubtfulAccount: "Doubtful Loan Account",
  negativeAccount: "Negative Loan Account",
  badAccount: "Bad Loan Account",
  amountHasEBarimt: "EBarimt calculate from Amount for Journal",
  interestAccount: "Interest Account",
  interestHasEBarimt: "EBarimt calculate from Interest for Journal",
  insuranceAccount: "Insurance Account",
  debtAccount: "Debt Account",
  feeIncomeAccount: "Fee Account",
  lossAccount: "Loss Account",
  lossHasEBarimt: "EBarimt calculate from Loss for Journal",
  eBarimtAccount: "EBarimt Account",
  organizationRegister: "Organization register",
  normalExpirationDay: "Normal classification day",
  expiredExpirationDay: "Expired classification begin day",
  doubtExpirationDay: "Doubtful classification begin day",
  negativeExpirationDay: "Negative classification begin day",
  badExpirationDay: "Bad classification begin day",
  minInterest: "Min interest of year",
  maxInterest: "Max interest of year",
  minTenor: "Min tenor",
  maxTenor: "Max tenor",
  minAmount: "Min amount",
  maxAmount: "Max amount",
  isAutoSendEBarimt: "Is send e-barimt auto",
  defaultGSCode: "DEFAULTGSCODE",
  isHasVat: "isHasVat",
  boardId: "Initial board",
  pipelineId: "Initial pipeline",
  stageId: "Initial stage",
  requirementsTxt: "Requirements Txt",
  customerDocumentsTxt: "Customer Documents Txt",
  companyDocumentsTxt: "Company Documents Txt",
};

export const LEASE_TYPES = {
  FINANCE: "finance",
  LINEAR: "linear",
  CREDIT: "credit",
  SAVING: "saving",
  ALL: ["finance", "linear", "credit", "saving"],
};

