export enum FrontlinePaths {
  Frontline = 'frontline',
  Inbox = '/inbox',
  TicketTags = '/ticket-tags',
  Calls = '/calls',
  IntegrationConfig = '/config',
  ErxesMessengerPreview = '/erxes-messenger-preview',
  Channels = '/channels',
  ChannelsCatchAll = '/channels/*',
  ChannelDetails = '/:id',
  ChannelMembers = '/:id/members',
  ChannelIntegrations = 'details/:id/:integrationType',
  FbAuth = '/fb-auth',
  ChannelPipelines = '/:id/pipelines',
  PipelineDetail = '/:id/pipelines/:pipelineId',
  PipelineDetailCatchAll = '/:id/pipelines/:pipelineId/*',
  ChannelResponsePage = '/:id/response',
  ResponseDetail = '/:id/response/:responseId',
  FormsCatchAll = '/forms/*',
  ChannelForms = '/:id/forms',
  FormDetail = '/:id/forms/:formId',
  FormPreview = '/form-preview',
  Reports = '/reports',
  Forms = '/forms',
  FormsCreate = '/:id/forms/create',
  FormSubmissions = '/:id/forms/submissions/:formId',
}
