export const CONVERSATION_RECEIVED = 'CONVERSATION_RECEIVED';

export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const SENDING_ATTACHMENT = 'SENDING_ATTACHMENT';
export const ATTACHMENT_SENT = 'ATTACHMENT_SENT';

export const MESSENGER_TOGGLE = 'MESSENGER_TOGGLE';
export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const CHANGE_CONVERSATION = 'CHANGE_CONVERSATION';

export const USER_RECEIVED = 'USER_RECEIVED';
export const USER_CHANGED = 'USER_CHANGED';

export const NOTIFICATION_RECEIVED = 'NOTIFICATION_RECEIVED';
