import { IPropertyMeta } from 'erxes-api-shared/core-modules';

// A customer is told apart by at least one of these.
const CUSTOMER_IDENTITY = 'identity';

export const properties: IPropertyMeta = {
  types: [
    {
      description: 'Customer',
      type: 'customer',
      systemFields: [
        {
          code: 'avatar',
          name: 'Avatar',
          type: 'file',
          visibleToCreateByDefault: true,
        },
        {
          code: 'firstName',
          name: 'First name',
          type: 'text',
          requiredGroup: CUSTOMER_IDENTITY,
          visibleToCreateByDefault: true,
        },
        { code: 'middleName', name: 'Middle name', type: 'text' },
        {
          code: 'lastName',
          name: 'Last name',
          type: 'text',
          visibleToCreateByDefault: true,
        },
        {
          code: 'code',
          name: 'Code',
          type: 'text',
          visibleToCreateByDefault: true,
        },
        {
          code: 'primaryEmail',
          name: 'Primary e-mail',
          type: 'text',
          requiredGroup: CUSTOMER_IDENTITY,
          visibleToCreateByDefault: true,
        },
        {
          code: 'primaryPhone',
          name: 'Primary phone',
          type: 'phone',
          requiredGroup: CUSTOMER_IDENTITY,
          visibleToCreateByDefault: true,
        },
        { code: 'sex', name: 'Pronoun', type: 'select', alwaysFilled: true },
        {
          code: 'birthDate',
          name: 'Birthday',
          type: 'date',
          visibleToCreateByDefault: true,
        },
        { code: 'position', name: 'Position', type: 'text' },
        { code: 'department', name: 'Department', type: 'text' },
        {
          code: 'hasAuthority',
          name: 'Has authority',
          type: 'select',
          alwaysFilled: true,
        },
        { code: 'leadStatus', name: 'Lead status', type: 'select' },
        {
          code: 'isSubscribed',
          name: 'Subscribed',
          type: 'select',
          alwaysFilled: true,
          visibleToCreateByDefault: true,
        },
        {
          code: 'ownerId',
          name: 'Owner',
          type: 'relation',
          alwaysFilled: true,
          visibleToCreateByDefault: true,
        },
        // customersAdd takes no tags; they are added after the customer exists.
        { code: 'tagIds', name: 'Tags', type: 'multiSelect', notOnCreate: true },
        {
          code: 'description',
          name: 'Description',
          type: 'textarea',
          visibleToCreateByDefault: true,
        },
      ],
    },
    {
      description: 'Company',
      type: 'company',
      systemFields: [
        { code: 'avatar', name: 'Logo', type: 'file' },
        { code: 'primaryName', name: 'Primary name', type: 'text' },
        { code: 'code', name: 'Code', type: 'text' },
        { code: 'primaryEmail', name: 'Primary e-mail', type: 'text' },
        { code: 'primaryPhone', name: 'Primary phone', type: 'phone' },
        { code: 'website', name: 'Website', type: 'text' },
        { code: 'size', name: 'Size', type: 'number' },
        { code: 'industry', name: 'Industries', type: 'multiSelect' },
        { code: 'businessType', name: 'Business type', type: 'select' },
        { code: 'location', name: 'Headquarters country', type: 'select' },
        { code: 'score', name: 'Score', type: 'number' },
        { code: 'isSubscribed', name: 'Subscribed', type: 'select' },
        { code: 'ownerId', name: 'Owner', type: 'relation' },
        { code: 'tagIds', name: 'Tags', type: 'multiSelect' },
        { code: 'description', name: 'Description', type: 'textarea' },
      ],
    },
    {
      description: 'Product & Service',
      type: 'product',
      systemFields: [
        { code: 'code', name: 'Code', type: 'text' },
        { code: 'name', name: 'Name', type: 'text' },
        { code: 'shortName', name: 'Short name', type: 'text' },
        { code: 'type', name: 'Type', type: 'select' },
        { code: 'categoryId', name: 'Category', type: 'relation' },
        { code: 'vendorId', name: 'Vendor', type: 'relation' },
        { code: 'status', name: 'Status', type: 'select' },
        { code: 'unitPrice', name: 'Unit price', type: 'number' },
        { code: 'uom', name: 'Unit of measurement', type: 'select' },
        {
          code: 'subUoms',
          name: 'Sub units of measurement',
          type: 'multiSelect',
        },
        { code: 'barcodes', name: 'Barcodes', type: 'multiSelect' },
        {
          code: 'barcodeDescription',
          name: 'Barcode description',
          type: 'textarea',
        },
        { code: 'attachment', name: 'Image', type: 'file' },
        { code: 'tagIds', name: 'Tags', type: 'multiSelect' },
        { code: 'description', name: 'Description', type: 'textarea' },
      ],
    },
    {
      description: 'Team member',
      type: 'user',
      systemFields: [
        { code: 'email', name: 'Primary e-mail', type: 'text' },
        { code: 'username', name: 'Username', type: 'text' },
        { code: 'details.avatar', name: 'Avatar', type: 'file' },
        { code: 'details.firstName', name: 'First name', type: 'text' },
        { code: 'details.middleName', name: 'Middle name', type: 'text' },
        { code: 'details.lastName', name: 'Last name', type: 'text' },
        { code: 'details.shortName', name: 'Short name', type: 'text' },
        { code: 'details.position', name: 'Position', type: 'text' },
        { code: 'details.birthDate', name: 'Birth date', type: 'date' },
        {
          code: 'details.workStartedDate',
          name: 'Work started date',
          type: 'date',
        },
        {
          code: 'details.operatorPhone',
          name: 'Operator phone',
          type: 'phone',
        },
        { code: 'details.location', name: 'Location', type: 'text' },
        { code: 'details.description', name: 'Description', type: 'textarea' },
      ],
    },
  ],
};
