import { IPropertyMeta } from 'erxes-api-shared/core-modules';

export const properties: IPropertyMeta = {
  types: [
    {
      description: 'Customer',
      type: 'customer',
      systemFields: [
        { code: 'avatar', name: 'Avatar', type: 'file' },
        { code: 'firstName', name: 'First name', type: 'text' },
        { code: 'middleName', name: 'Middle name', type: 'text' },
        { code: 'lastName', name: 'Last name', type: 'text' },
        { code: 'code', name: 'Code', type: 'text' },
        { code: 'primaryEmail', name: 'Primary e-mail', type: 'text' },
        { code: 'primaryPhone', name: 'Primary phone', type: 'phone' },
        { code: 'sex', name: 'Pronoun', type: 'select' },
        { code: 'birthDate', name: 'Birthday', type: 'date' },
        { code: 'position', name: 'Position', type: 'text' },
        { code: 'department', name: 'Department', type: 'text' },
        { code: 'hasAuthority', name: 'Has authority', type: 'select' },
        { code: 'leadStatus', name: 'Lead status', type: 'select' },
        { code: 'isSubscribed', name: 'Subscribed', type: 'select' },
        { code: 'ownerId', name: 'Owner', type: 'relation' },
        { code: 'tagIds', name: 'Tags', type: 'multiSelect' },
        { code: 'description', name: 'Description', type: 'textarea' },
      ],
    },
    {
      description: 'Company',
      type: 'company',
      systemFields: [
        { code: 'avatar', name: 'Logo', type: 'file' },
        { code: 'primaryName', name: 'Primary name', type: 'text' },
        { code: 'code', name: 'Code', type: 'text' },
        { code: 'primaryEmail', name: 'Primary e-mail', type: 'text' },
        { code: 'primaryPhone', name: 'Primary phone', type: 'phone' },
        { code: 'website', name: 'Website', type: 'text' },
        { code: 'size', name: 'Size', type: 'number' },
        { code: 'industry', name: 'Industries', type: 'multiSelect' },
        { code: 'businessType', name: 'Business type', type: 'select' },
        { code: 'location', name: 'Headquarters country', type: 'select' },
        { code: 'score', name: 'Score', type: 'number' },
        { code: 'isSubscribed', name: 'Subscribed', type: 'select' },
        { code: 'ownerId', name: 'Owner', type: 'relation' },
        { code: 'tagIds', name: 'Tags', type: 'multiSelect' },
        { code: 'description', name: 'Description', type: 'textarea' },
      ],
    },
    {
      description: 'Product & Service',
      type: 'product',
      systemFields: [
        { code: 'code', name: 'Code', type: 'text' },
        { code: 'name', name: 'Name', type: 'text' },
        { code: 'shortName', name: 'Short name', type: 'text' },
        { code: 'type', name: 'Type', type: 'select' },
        { code: 'categoryId', name: 'Category', type: 'relation' },
        { code: 'vendorId', name: 'Vendor', type: 'relation' },
        { code: 'status', name: 'Status', type: 'select' },
        { code: 'unitPrice', name: 'Unit price', type: 'number' },
        { code: 'uom', name: 'Unit of measurement', type: 'select' },
        {
          code: 'subUoms',
          name: 'Sub units of measurement',
          type: 'multiSelect',
        },
        { code: 'barcodes', name: 'Barcodes', type: 'multiSelect' },
        {
          code: 'barcodeDescription',
          name: 'Barcode description',
          type: 'textarea',
        },
        { code: 'attachment', name: 'Image', type: 'file' },
        { code: 'tagIds', name: 'Tags', type: 'multiSelect' },
        { code: 'description', name: 'Description', type: 'textarea' },
      ],
    },
    {
      description: 'Team member',
      type: 'user',
      systemFields: [
        { code: 'email', name: 'Primary e-mail', type: 'text' },
        { code: 'username', name: 'Username', type: 'text' },
        { code: 'details.avatar', name: 'Avatar', type: 'file' },
        { code: 'details.firstName', name: 'First name', type: 'text' },
        { code: 'details.middleName', name: 'Middle name', type: 'text' },
        { code: 'details.lastName', name: 'Last name', type: 'text' },
        { code: 'details.shortName', name: 'Short name', type: 'text' },
        { code: 'details.position', name: 'Position', type: 'text' },
        { code: 'details.birthDate', name: 'Birth date', type: 'date' },
        {
          code: 'details.workStartedDate',
          name: 'Work started date',
          type: 'date',
        },
        {
          code: 'details.operatorPhone',
          name: 'Operator phone',
          type: 'phone',
        },
        { code: 'details.location', name: 'Location', type: 'text' },
        { code: 'details.description', name: 'Description', type: 'textarea' },
      ],
    },
  ],
};
