#!/bin/sh

ENV="$(cat <<EOF
  window.env = {
      NEXT_PUBLIC_MAIN_API_DOMAIN: "$NEXT_PUBLIC_MAIN_API_DOMAIN",
      NEXT_PUBLIC_MAIN_SUBS_DOMAIN: "$NEXT_PUBLIC_MAIN_SUBS_DOMAIN",
      NEXT_PUBLIC_SERVER_API_DOMAIN: "$NEXT_PUBLIC_SERVER_API_DOMAIN",
      NEXT_PUBLIC_SERVER_DOMAIN: "$NEXT_PUBLIC_SERVER_DOMAIN",
      NEXT_PUBLIC_CALLS_APP_ID: "$NEXT_PUBLIC_CALLS_APP_ID",
      NEXT_PUBLIC_CALLS_APP_SECRET: "$NEXT_PUBLIC_CALLS_APP_SECRET",

  }
EOF
)"

echo $ENV > /web-call/public/js/env.js

exec "$@"
