
*

!apps/knowledge-base
!frontend/libs/erxes-ui/src

**/node_modules
**/.next
**/*.tsbuildinfo
apps/knowledge-base/.env
apps/knowledge-base/.env.*
!apps/knowledge-base/.env.example
apps/knowledge-base/next-env.d.ts
apps/knowledge-base/coverage
