FROM node:12-slim
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y \
    rsync python build-essential && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /erxes-api
COPY yarn.lock package.json ./
RUN yarn install
CMD ["yarn", "dev"]