name: ElkSyncer CI

on:
  push:
    branches:
      - priuscenter
    paths:
      - 'elkSyncer/**'
      - '.github/workflows/elk_syncer.yaml'

  pull_request:
    branches:
      - priuscenter
    paths:
      - 'elkSyncer/**'
      - '.github/workflows/elk_syncer.yaml'

jobs:
  elkSyncer:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Build docker image
      if: github.event_name == 'push' && ( github.ref == 'refs/heads/priuscenter' )
      run: |
        cd elkSyncer
        echo ${{ secrets.REGISTRY_TOKEN }} | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
        docker build -t ${{ secrets.REGISTRY_URL }}/erxes-enterprise/erxes-elksyncer:${GITHUB_REF#refs/heads/} -f Dockerfile .
        docker push ${{ secrets.REGISTRY_URL }}/erxes-enterprise/erxes-elksyncer:${GITHUB_REF#refs/heads/}
