name: Integrations CI

on:
  push:
    branches:
      - "**"
    paths:
      - "integrations/**"
      - "!integrations/**.md"
      - "!.github/**"
      - ".github/workflows/integrations.yaml"
  pull_request:
    branches:
      - master
      - develop
    paths:
      - "integrations/**"
      - "!integrations/**.md"
      - "!.github/**"
      - ".github/workflows/integrations.yaml"

jobs:
  integrations:
    runs-on: ubuntu-18.04

    services:
      mongodb:
        image: mongo:4.0
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.19.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.19.x

      # https://github.com/actions/cache/blob/master/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-integrations-${{ hashFiles('yarn.lock', 'integrations/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-integrations-
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          yarn install
          cd integrations
          yarn install --frozen-lockfile

      - name: Lint
        run: |
          yarn lint integrations

      - name: Test
        run: |
          cd integrations
          yarn test
        env:
          TEST_MONGO_URL: mongodb://localhost/test
          GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID
          GOOGLE_CLIENT_SECRET: GOOGLE_CLIENT_SECRET
          ENCRYPTION_KEY: aksljdklwjdaklsjdkwljaslkdjwkljd
          DOMAIN: http://localhost:3400
          MAIN_APP_DOMAIN: http://localhost:3400

      - name: Build
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' )
        run: |
          cd integrations
          rm -rf node_modules
          yarn install --frozen-lockfile --production
          yarn build

      - name: Build docker image
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' )
        run: |
          cd integrations
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker build -t erxes/erxes-integrations:${GITHUB_REF#refs/heads/} -f Dockerfile .
          docker push erxes/erxes-integrations:${GITHUB_REF#refs/heads/}
