import { StyleSheet } from '@react-pdf/renderer';
import { COLORS, styles as sharedStyles } from '../../itinerary/pdf/styles';
import { PDF_FONT_FAMILY } from '../../itinerary/pdf/fonts';

export { COLORS, sharedStyles };

export const styles = StyleSheet.create({
  coverPage: {
    fontFamily: PDF_FONT_FAMILY,
    padding: 0,
    margin: 0,
  },
  coverWrapper: {
    width: 595.28,
    height: 841.89,
    position: 'relative',
  },
  coverBackgroundImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 595.28,
    height: 841.89,
  },
  coverOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 595.28,
    height: 841.89,
    backgroundColor: '#000000',
    opacity: 0.22,
  },
  coverLogoRow: {
    position: 'absolute',
    top: 30,
    left: 30,
    flexDirection: 'row',
    alignItems: 'center',
  },
  coverLogo: {
    width: 64,
    height: 64,
    objectFit: 'contain',
  },
  coverInfoBox: {
    position: 'absolute',
    left: 30,
    right: 30,
    bottom: 30,
    borderRadius: 4,
    paddingVertical: 30,
    paddingHorizontal: 28,
  },
  coverEyebrow: {
    fontSize: 10,
    color: COLORS.white,
    letterSpacing: 2.2,
    marginBottom: 10,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  coverTitle: {
    fontSize: 26,
    fontFamily: PDF_FONT_FAMILY,
    fontWeight: 'bold',
    color: COLORS.white,
    lineHeight: 1.3,
    marginBottom: 14,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  coverDivider: {
    width: 80,
    height: 2,
    backgroundColor: COLORS.white,
    alignSelf: 'center',
    marginBottom: 14,
  },
  coverDateText: {
    fontSize: 13,
    color: COLORS.white,
    fontFamily: PDF_FONT_FAMILY,
    fontWeight: 'bold',
    fontStyle: 'italic',
    textAlign: 'center',
  },
  page: {
    fontFamily: PDF_FONT_FAMILY,
    fontSize: 10,
    color: COLORS.text,
    paddingTop: 34,
    paddingBottom: 50,
    paddingHorizontal: 40,
    backgroundColor: COLORS.white,
  },
  pageTitle: {
    fontSize: 20,
    fontFamily: PDF_FONT_FAMILY,
    fontWeight: 'bold',
    color: COLORS.black,
    letterSpacing: 1,
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  titleDivider: {
    width: 78,
    height: 2,
    marginBottom: 14,
  },
  introSection: {
    marginBottom: 18,
  },
  overviewEyebrow: {
    fontSize: 10,
    fontFamily: PDF_FONT_FAMILY,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 1.4,
    marginBottom: 6,
  },
  overviewText: {
    fontSize: 9,
    color: COLORS.text,
    lineHeight: 1.6,
  },
  metaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: 12,
    columnGap: 16,
    marginBottom: 18,
  },
  metaCard: {
    width: '48%',
    minHeight: 34,
  },
  metaLabel: {
    fontSize: 8,
    color: COLORS.gray,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  metaValue: {
    fontSize: 11,
    color: COLORS.black,
    fontFamily: PDF_FONT_FAMILY,
    fontWeight: 'bold',
    lineHeight: 1.4,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: COLORS.lightGray,
    marginBottom: 16,
  },
  section: {
    marginBottom: 16,
  },
  sectionHeadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  sectionAccentBar: {
    width: 18,
    height: 2,
  },
  sectionTitle: {
    fontSize: 12,
    fontFamily: PDF_FONT_FAMILY,
    fontWeight: 'bold',
    color: COLORS.black,
    textTransform: 'uppercase',
  },
  sectionBody: {
    paddingTop: 2,
  },
  fallbackBodyText: {
    fontSize: 9,
    color: COLORS.text,
    lineHeight: 1.7,
  },
  pricingCard: {
    paddingTop: 4,
    marginBottom: 12,
  },
  pricingHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
    gap: 8,
  },
  pricingTitle: {
    flex: 1,
    fontSize: 10,
    fontFamily: PDF_FONT_FAMILY,
    fontWeight: 'bold',
    color: COLORS.black,
    textTransform: 'uppercase',
  },
  pricingRange: {
    fontSize: 8,
    textTransform: 'uppercase',
    fontFamily: PDF_FONT_FAMILY,
    fontWeight: 'bold',
  },
  pricingBodyRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: 8,
    columnGap: 16,
    marginBottom: 8,
  },
  pricingFact: {
    width: '47%',
  },
  pricingFactLabel: {
    fontSize: 8,
    color: COLORS.gray,
    fontFamily: PDF_FONT_FAMILY,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
    marginBottom: 3,
  },
  pricingFactValue: {
    fontSize: 9,
    color: COLORS.text,
    fontFamily: PDF_FONT_FAMILY,
    fontWeight: 'bold',
  },
  pricingNote: {
    fontSize: 8.5,
    color: COLORS.textLight,
    lineHeight: 1.6,
  },
  pricingDivider: {
    height: 1,
    backgroundColor: COLORS.lightGray,
    marginTop: 12,
  },
});
